<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/swap/v1/events.proto

namespace Decimal\Swap\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * EventRedeemSwap defines event emitted when cross-chain swap is redeemed.
 *
 * Generated from protobuf message <code>decimal.swap.v1.EventRedeemSwap</code>
 */
class EventRedeemSwap extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender"];</code>
     */
    protected $sender = '';
    /**
     * Generated from protobuf field <code>string from = 2 [json_name = "from"];</code>
     */
    protected $from = '';
    /**
     * Generated from protobuf field <code>uint32 dest_chain = 3 [json_name = "destChain"];</code>
     */
    protected $dest_chain = 0;
    /**
     * Generated from protobuf field <code>string recipient = 4 [json_name = "recipient"];</code>
     */
    protected $recipient = '';
    /**
     * Generated from protobuf field <code>string amount = 5 [json_name = "amount"];</code>
     */
    protected $amount = '';
    /**
     * Generated from protobuf field <code>string transaction_number = 6 [json_name = "transactionNumber"];</code>
     */
    protected $transaction_number = '';
    /**
     * Generated from protobuf field <code>string token_symbol = 7 [json_name = "tokenSymbol"];</code>
     */
    protected $token_symbol = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sender
     *     @type string $from
     *     @type int $dest_chain
     *     @type string $recipient
     *     @type string $amount
     *     @type string $transaction_number
     *     @type string $token_symbol
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Decimal\Swap\V1\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender"];</code>
     * @return string
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender"];</code>
     * @param string $var
     * @return $this
     */
    public function setSender($var)
    {
        GPBUtil::checkString($var, True);
        $this->sender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from = 2 [json_name = "from"];</code>
     * @return string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>string from = 2 [json_name = "from"];</code>
     * @param string $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 dest_chain = 3 [json_name = "destChain"];</code>
     * @return int
     */
    public function getDestChain()
    {
        return $this->dest_chain;
    }

    /**
     * Generated from protobuf field <code>uint32 dest_chain = 3 [json_name = "destChain"];</code>
     * @param int $var
     * @return $this
     */
    public function setDestChain($var)
    {
        GPBUtil::checkUint32($var);
        $this->dest_chain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string recipient = 4 [json_name = "recipient"];</code>
     * @return string
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * Generated from protobuf field <code>string recipient = 4 [json_name = "recipient"];</code>
     * @param string $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkString($var, True);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string amount = 5 [json_name = "amount"];</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>string amount = 5 [json_name = "amount"];</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_number = 6 [json_name = "transactionNumber"];</code>
     * @return string
     */
    public function getTransactionNumber()
    {
        return $this->transaction_number;
    }

    /**
     * Generated from protobuf field <code>string transaction_number = 6 [json_name = "transactionNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token_symbol = 7 [json_name = "tokenSymbol"];</code>
     * @return string
     */
    public function getTokenSymbol()
    {
        return $this->token_symbol;
    }

    /**
     * Generated from protobuf field <code>string token_symbol = 7 [json_name = "tokenSymbol"];</code>
     * @param string $var
     * @return $this
     */
    public function setTokenSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_symbol = $var;

        return $this;
    }

}

