<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/swap/v1/tx.proto

namespace Decimal\Swap\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgInitializeSwapResponse defines the Msg/InitializeSwap response type.
 *
 * Generated from protobuf message <code>decimal.swap.v1.MsgInitializeSwapResponse</code>
 */
class MsgInitializeSwapResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Decimal\Swap\V1\Tx::initOnce();
        parent::__construct($data);
    }

}

