<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/crypto/keyring/v1/record.proto

namespace Cosmos\Crypto\Keyring\V1\Record;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Item is a keyring item stored in a keyring backend.
 * Local item
 *
 * Generated from protobuf message <code>cosmos.crypto.keyring.v1.Record.Local</code>
 */
class Local extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Any priv_key = 1 [json_name = "privKey"];</code>
     */
    protected $priv_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Any $priv_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Crypto\Keyring\V1\Record::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any priv_key = 1 [json_name = "privKey"];</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getPrivKey()
    {
        return $this->priv_key;
    }

    public function hasPrivKey()
    {
        return isset($this->priv_key);
    }

    public function clearPrivKey()
    {
        unset($this->priv_key);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any priv_key = 1 [json_name = "privKey"];</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setPrivKey($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->priv_key = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Local::class, \Cosmos\Crypto\Keyring\V1\Record_Local::class);

