<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/authz/v1beta1/tx.proto

namespace Cosmos\Authz\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgRevokeResponse defines the Msg/MsgRevokeResponse response type.
 *
 * Generated from protobuf message <code>cosmos.authz.v1beta1.MsgRevokeResponse</code>
 */
class MsgRevokeResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Authz\V1Beta1\Tx::initOnce();
        parent::__construct($data);
    }

}

