<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/tx/v1beta1/service.proto

namespace Cosmos\Tx\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * BroadcastTxRequest is the request type for the Service.BroadcastTxRequest
 * RPC method.
 *
 * Generated from protobuf message <code>cosmos.tx.v1beta1.BroadcastTxRequest</code>
 */
class BroadcastTxRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * tx_bytes is the raw transaction.
     *
     * Generated from protobuf field <code>bytes tx_bytes = 1 [json_name = "txBytes"];</code>
     */
    protected $tx_bytes = '';
    /**
     * Generated from protobuf field <code>.cosmos.tx.v1beta1.BroadcastMode mode = 2 [json_name = "mode"];</code>
     */
    protected $mode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tx_bytes
     *           tx_bytes is the raw transaction.
     *     @type int $mode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Tx\V1Beta1\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * tx_bytes is the raw transaction.
     *
     * Generated from protobuf field <code>bytes tx_bytes = 1 [json_name = "txBytes"];</code>
     * @return string
     */
    public function getTxBytes()
    {
        return $this->tx_bytes;
    }

    /**
     * tx_bytes is the raw transaction.
     *
     * Generated from protobuf field <code>bytes tx_bytes = 1 [json_name = "txBytes"];</code>
     * @param string $var
     * @return $this
     */
    public function setTxBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->tx_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cosmos.tx.v1beta1.BroadcastMode mode = 2 [json_name = "mode"];</code>
     * @return int
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>.cosmos.tx.v1beta1.BroadcastMode mode = 2 [json_name = "mode"];</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkEnum($var, \Cosmos\Tx\V1beta1\BroadcastMode::class);
        $this->mode = $var;

        return $this;
    }

}

