<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/tx/v1beta1/service.proto

namespace Cosmos\Tx\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * GetTxsEventResponse is the response type for the Service.TxsByEvents
 * RPC method.
 *
 * Generated from protobuf message <code>cosmos.tx.v1beta1.GetTxsEventResponse</code>
 */
class GetTxsEventResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * txs is the list of queried transactions.
     *
     * Generated from protobuf field <code>repeated .cosmos.tx.v1beta1.Tx txs = 1 [json_name = "txs"];</code>
     */
    private $txs;
    /**
     * tx_responses is the list of queried TxResponses.
     *
     * Generated from protobuf field <code>repeated .cosmos.base.abci.v1beta1.TxResponse tx_responses = 2 [json_name = "txResponses"];</code>
     */
    private $tx_responses;
    /**
     * pagination defines a pagination for the response.
     * Deprecated post v0.46.x: use total instead.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 3 [json_name = "pagination", deprecated = true];</code>
     * @deprecated
     */
    protected $pagination = null;
    /**
     * total is total number of results available
     *
     * Generated from protobuf field <code>uint64 total = 4 [json_name = "total"];</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cosmos\Tx\V1beta1\Tx[]|\Google\Protobuf\Internal\RepeatedField $txs
     *           txs is the list of queried transactions.
     *     @type \Cosmos\Base\Abci\V1beta1\TxResponse[]|\Google\Protobuf\Internal\RepeatedField $tx_responses
     *           tx_responses is the list of queried TxResponses.
     *     @type \Cosmos\Base\Query\V1beta1\PageResponse $pagination
     *           pagination defines a pagination for the response.
     *           Deprecated post v0.46.x: use total instead.
     *     @type int|string $total
     *           total is total number of results available
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Tx\V1Beta1\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * txs is the list of queried transactions.
     *
     * Generated from protobuf field <code>repeated .cosmos.tx.v1beta1.Tx txs = 1 [json_name = "txs"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTxs()
    {
        return $this->txs;
    }

    /**
     * txs is the list of queried transactions.
     *
     * Generated from protobuf field <code>repeated .cosmos.tx.v1beta1.Tx txs = 1 [json_name = "txs"];</code>
     * @param \Cosmos\Tx\V1beta1\Tx[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTxs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cosmos\Tx\V1beta1\Tx::class);
        $this->txs = $arr;

        return $this;
    }

    /**
     * tx_responses is the list of queried TxResponses.
     *
     * Generated from protobuf field <code>repeated .cosmos.base.abci.v1beta1.TxResponse tx_responses = 2 [json_name = "txResponses"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTxResponses()
    {
        return $this->tx_responses;
    }

    /**
     * tx_responses is the list of queried TxResponses.
     *
     * Generated from protobuf field <code>repeated .cosmos.base.abci.v1beta1.TxResponse tx_responses = 2 [json_name = "txResponses"];</code>
     * @param \Cosmos\Base\Abci\V1beta1\TxResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTxResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cosmos\Base\Abci\V1beta1\TxResponse::class);
        $this->tx_responses = $arr;

        return $this;
    }

    /**
     * pagination defines a pagination for the response.
     * Deprecated post v0.46.x: use total instead.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 3 [json_name = "pagination", deprecated = true];</code>
     * @return \Cosmos\Base\Query\V1beta1\PageResponse|null
     * @deprecated
     */
    public function getPagination()
    {
        @trigger_error('pagination is deprecated.', E_USER_DEPRECATED);
        return $this->pagination;
    }

    public function hasPagination()
    {
        @trigger_error('pagination is deprecated.', E_USER_DEPRECATED);
        return isset($this->pagination);
    }

    public function clearPagination()
    {
        @trigger_error('pagination is deprecated.', E_USER_DEPRECATED);
        unset($this->pagination);
    }

    /**
     * pagination defines a pagination for the response.
     * Deprecated post v0.46.x: use total instead.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 3 [json_name = "pagination", deprecated = true];</code>
     * @param \Cosmos\Base\Query\V1beta1\PageResponse $var
     * @return $this
     * @deprecated
     */
    public function setPagination($var)
    {
        @trigger_error('pagination is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \Cosmos\Base\Query\V1beta1\PageResponse::class);
        $this->pagination = $var;

        return $this;
    }

    /**
     * total is total number of results available
     *
     * Generated from protobuf field <code>uint64 total = 4 [json_name = "total"];</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * total is total number of results available
     *
     * Generated from protobuf field <code>uint64 total = 4 [json_name = "total"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint64($var);
        $this->total = $var;

        return $this;
    }

}

