<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/lightclients/solomachine/v1/solomachine.proto

namespace Ibc\Lightclients\Solomachine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ChannelStateData returns the SignBytes data for channel state
 * verification.
 *
 * Generated from protobuf message <code>ibc.lightclients.solomachine.v1.ChannelStateData</code>
 */
class ChannelStateData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes path = 1 [json_name = "path"];</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>.ibc.core.channel.v1.Channel channel = 2 [json_name = "channel"];</code>
     */
    protected $channel = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *     @type \Ibc\Core\Channel\V1\Channel $channel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Lightclients\Solomachine\V1\Solomachine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes path = 1 [json_name = "path"];</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>bytes path = 1 [json_name = "path"];</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, False);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ibc.core.channel.v1.Channel channel = 2 [json_name = "channel"];</code>
     * @return \Ibc\Core\Channel\V1\Channel|null
     */
    public function getChannel()
    {
        return $this->channel;
    }

    public function hasChannel()
    {
        return isset($this->channel);
    }

    public function clearChannel()
    {
        unset($this->channel);
    }

    /**
     * Generated from protobuf field <code>.ibc.core.channel.v1.Channel channel = 2 [json_name = "channel"];</code>
     * @param \Ibc\Core\Channel\V1\Channel $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Core\Channel\V1\Channel::class);
        $this->channel = $var;

        return $this;
    }

}

