<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/lightclients/solomachine/v1/solomachine.proto

namespace Ibc\Lightclients\Solomachine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SignatureAndData contains a signature and the data signed over to create that
 * signature.
 *
 * Generated from protobuf message <code>ibc.lightclients.solomachine.v1.SignatureAndData</code>
 */
class SignatureAndData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes signature = 1 [json_name = "signature"];</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>.ibc.lightclients.solomachine.v1.DataType data_type = 2 [json_name = "dataType", (.gogoproto.moretags) = "yaml:\"data_type\""];</code>
     */
    protected $data_type = 0;
    /**
     * Generated from protobuf field <code>bytes data = 3 [json_name = "data"];</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>uint64 timestamp = 4 [json_name = "timestamp"];</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signature
     *     @type int $data_type
     *     @type string $data
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Lightclients\Solomachine\V1\Solomachine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes signature = 1 [json_name = "signature"];</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 1 [json_name = "signature"];</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ibc.lightclients.solomachine.v1.DataType data_type = 2 [json_name = "dataType", (.gogoproto.moretags) = "yaml:\"data_type\""];</code>
     * @return int
     */
    public function getDataType()
    {
        return $this->data_type;
    }

    /**
     * Generated from protobuf field <code>.ibc.lightclients.solomachine.v1.DataType data_type = 2 [json_name = "dataType", (.gogoproto.moretags) = "yaml:\"data_type\""];</code>
     * @param int $var
     * @return $this
     */
    public function setDataType($var)
    {
        GPBUtil::checkEnum($var, \Ibc\Lightclients\Solomachine\V1\DataType::class);
        $this->data_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 3 [json_name = "data"];</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 3 [json_name = "data"];</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4 [json_name = "timestamp"];</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4 [json_name = "timestamp"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

}

