<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/authz/v1beta1/query.proto

namespace Cosmos\Authz\V1beta1\GPBMetadata;

class Query
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Google\Api\GPBMetadata\Annotations::initOnce();
        \Cosmos\Base\Query\V1beta1\GPBMetadata\Pagination::initOnce();
        \Cosmos\Authz\V1beta1\GPBMetadata\Authz::initOnce();
        $pool->internalAddGeneratedFile(
            '
™
 cosmos/authz/v1beta1/query.protocosmos.authz.v1beta1*cosmos/base/query/v1beta1/pagination.proto cosmos/authz/v1beta1/authz.proto"≤
QueryGrantsRequest
granter (	Rgranter
grantee (	Rgrantee 
msg_type_url (	R
msgTypeUrlF

pagination (2&.cosmos.base.query.v1beta1.PageRequestR
pagination"ì
QueryGrantsResponse3
grants (2.cosmos.authz.v1beta1.GrantRgrantsG

pagination (2\'.cosmos.base.query.v1beta1.PageResponseR
pagination2ç
QueryÉ
Grants(.cosmos.authz.v1beta1.QueryGrantsRequest).cosmos.authz.v1beta1.QueryGrantsResponse"$Ç”‰ì/cosmos/authz/v1beta1/grantsBæ
com.cosmos.authz.v1beta1B
QueryProtoPZ$github.com/cosmos/cosmos-sdk/x/authz¢CAX™Cosmos.Authz.V1beta1 Cosmos\\Authz\\V1beta1‚ Cosmos\\Authz\\V1beta1\\GPBMetadataÍCosmos::Authz::V1beta1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

