<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/interchain_accounts/v1/genesis.proto

namespace Ibc\Applications\Interchain_accounts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ActiveChannel contains a connection ID, port ID and associated active channel ID
 *
 * Generated from protobuf message <code>ibc.applications.interchain_accounts.v1.ActiveChannel</code>
 */
class ActiveChannel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string connection_id = 1 [json_name = "connectionId", (.gogoproto.moretags) = "yaml:\"connection_id\""];</code>
     */
    protected $connection_id = '';
    /**
     * Generated from protobuf field <code>string port_id = 2 [json_name = "portId", (.gogoproto.moretags) = "yaml:\"port_id\""];</code>
     */
    protected $port_id = '';
    /**
     * Generated from protobuf field <code>string channel_id = 3 [json_name = "channelId", (.gogoproto.moretags) = "yaml:\"channel_id\""];</code>
     */
    protected $channel_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $connection_id
     *     @type string $port_id
     *     @type string $channel_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Applications\InterchainAccounts\V1\Genesis::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string connection_id = 1 [json_name = "connectionId", (.gogoproto.moretags) = "yaml:\"connection_id\""];</code>
     * @return string
     */
    public function getConnectionId()
    {
        return $this->connection_id;
    }

    /**
     * Generated from protobuf field <code>string connection_id = 1 [json_name = "connectionId", (.gogoproto.moretags) = "yaml:\"connection_id\""];</code>
     * @param string $var
     * @return $this
     */
    public function setConnectionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->connection_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string port_id = 2 [json_name = "portId", (.gogoproto.moretags) = "yaml:\"port_id\""];</code>
     * @return string
     */
    public function getPortId()
    {
        return $this->port_id;
    }

    /**
     * Generated from protobuf field <code>string port_id = 2 [json_name = "portId", (.gogoproto.moretags) = "yaml:\"port_id\""];</code>
     * @param string $var
     * @return $this
     */
    public function setPortId($var)
    {
        GPBUtil::checkString($var, True);
        $this->port_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel_id = 3 [json_name = "channelId", (.gogoproto.moretags) = "yaml:\"channel_id\""];</code>
     * @return string
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }

    /**
     * Generated from protobuf field <code>string channel_id = 3 [json_name = "channelId", (.gogoproto.moretags) = "yaml:\"channel_id\""];</code>
     * @param string $var
     * @return $this
     */
    public function setChannelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel_id = $var;

        return $this;
    }

}

