<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/gov/v1beta1/query.proto

namespace Cosmos\Gov\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryTallyResultRequest is the request type for the Query/Tally RPC method.
 *
 * Generated from protobuf message <code>cosmos.gov.v1beta1.QueryTallyResultRequest</code>
 */
class QueryTallyResultRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * proposal_id defines the unique id of the proposal.
     *
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId"];</code>
     */
    protected $proposal_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $proposal_id
     *           proposal_id defines the unique id of the proposal.
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Gov\V1beta1\GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * proposal_id defines the unique id of the proposal.
     *
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId"];</code>
     * @return int|string
     */
    public function getProposalId()
    {
        return $this->proposal_id;
    }

    /**
     * proposal_id defines the unique id of the proposal.
     *
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setProposalId($var)
    {
        GPBUtil::checkUint64($var);
        $this->proposal_id = $var;

        return $this;
    }

}

