<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/gov/v1beta1/gov.proto

namespace Cosmos\Gov\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * VotingParams defines the params for voting on governance proposals.
 *
 * Generated from protobuf message <code>cosmos.gov.v1beta1.VotingParams</code>
 */
class VotingParams extends \Google\Protobuf\Internal\Message
{
    /**
     *  Length of the voting period.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration voting_period = 1 [json_name = "votingPeriod", (.gogoproto.nullable) = false, (.gogoproto.jsontag) = "voting_period,omitempty", (.gogoproto.moretags) = "yaml:\"voting_period\"", (.gogoproto.stdduration) = true];</code>
     */
    protected $voting_period = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Duration $voting_period
     *            Length of the voting period.
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Gov\V1beta1\GPBMetadata\Gov::initOnce();
        parent::__construct($data);
    }

    /**
     *  Length of the voting period.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration voting_period = 1 [json_name = "votingPeriod", (.gogoproto.nullable) = false, (.gogoproto.jsontag) = "voting_period,omitempty", (.gogoproto.moretags) = "yaml:\"voting_period\"", (.gogoproto.stdduration) = true];</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getVotingPeriod()
    {
        return $this->voting_period;
    }

    public function hasVotingPeriod()
    {
        return isset($this->voting_period);
    }

    public function clearVotingPeriod()
    {
        unset($this->voting_period);
    }

    /**
     *  Length of the voting period.
     *
     * Generated from protobuf field <code>.google.protobuf.Duration voting_period = 1 [json_name = "votingPeriod", (.gogoproto.nullable) = false, (.gogoproto.jsontag) = "voting_period,omitempty", (.gogoproto.moretags) = "yaml:\"voting_period\"", (.gogoproto.stdduration) = true];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setVotingPeriod($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->voting_period = $var;

        return $this;
    }

}

