<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/staking/v1beta1/staking.proto

namespace Cosmos\Staking\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Delegation represents the bond with tokens held by an account. It is
 * owned by one delegator, and is associated with the voting power of one
 * validator.
 *
 * Generated from protobuf message <code>cosmos.staking.v1beta1.Delegation</code>
 */
class Delegation extends \Google\Protobuf\Internal\Message
{
    /**
     * delegator_address is the bech32-encoded address of the delegator.
     *
     * Generated from protobuf field <code>string delegator_address = 1 [json_name = "delegatorAddress", (.gogoproto.moretags) = "yaml:\"delegator_address\""];</code>
     */
    protected $delegator_address = '';
    /**
     * validator_address is the bech32-encoded address of the validator.
     *
     * Generated from protobuf field <code>string validator_address = 2 [json_name = "validatorAddress", (.gogoproto.moretags) = "yaml:\"validator_address\""];</code>
     */
    protected $validator_address = '';
    /**
     * shares define the delegation shares received.
     *
     * Generated from protobuf field <code>string shares = 3 [json_name = "shares", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    protected $shares = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $delegator_address
     *           delegator_address is the bech32-encoded address of the delegator.
     *     @type string $validator_address
     *           validator_address is the bech32-encoded address of the validator.
     *     @type string $shares
     *           shares define the delegation shares received.
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Staking\V1beta1\GPBMetadata\Staking::initOnce();
        parent::__construct($data);
    }

    /**
     * delegator_address is the bech32-encoded address of the delegator.
     *
     * Generated from protobuf field <code>string delegator_address = 1 [json_name = "delegatorAddress", (.gogoproto.moretags) = "yaml:\"delegator_address\""];</code>
     * @return string
     */
    public function getDelegatorAddress()
    {
        return $this->delegator_address;
    }

    /**
     * delegator_address is the bech32-encoded address of the delegator.
     *
     * Generated from protobuf field <code>string delegator_address = 1 [json_name = "delegatorAddress", (.gogoproto.moretags) = "yaml:\"delegator_address\""];</code>
     * @param string $var
     * @return $this
     */
    public function setDelegatorAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->delegator_address = $var;

        return $this;
    }

    /**
     * validator_address is the bech32-encoded address of the validator.
     *
     * Generated from protobuf field <code>string validator_address = 2 [json_name = "validatorAddress", (.gogoproto.moretags) = "yaml:\"validator_address\""];</code>
     * @return string
     */
    public function getValidatorAddress()
    {
        return $this->validator_address;
    }

    /**
     * validator_address is the bech32-encoded address of the validator.
     *
     * Generated from protobuf field <code>string validator_address = 2 [json_name = "validatorAddress", (.gogoproto.moretags) = "yaml:\"validator_address\""];</code>
     * @param string $var
     * @return $this
     */
    public function setValidatorAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->validator_address = $var;

        return $this;
    }

    /**
     * shares define the delegation shares received.
     *
     * Generated from protobuf field <code>string shares = 3 [json_name = "shares", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     * @return string
     */
    public function getShares()
    {
        return $this->shares;
    }

    /**
     * shares define the delegation shares received.
     *
     * Generated from protobuf field <code>string shares = 3 [json_name = "shares", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     * @param string $var
     * @return $this
     */
    public function setShares($var)
    {
        GPBUtil::checkString($var, True);
        $this->shares = $var;

        return $this;
    }

}

