<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/staking/v1beta1/staking.proto

namespace Cosmos\Staking\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DVVTriplet is struct that just has a delegator-validator-validator triplet
 * with no other data. It is intended to be used as a marshalable pointer. For
 * example, a DVVTriplet can be used to construct the key to getting a
 * Redelegation from state.
 *
 * Generated from protobuf message <code>cosmos.staking.v1beta1.DVVTriplet</code>
 */
class DVVTriplet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string delegator_address = 1 [json_name = "delegatorAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $delegator_address = '';
    /**
     * Generated from protobuf field <code>string validator_src_address = 2 [json_name = "validatorSrcAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $validator_src_address = '';
    /**
     * Generated from protobuf field <code>string validator_dst_address = 3 [json_name = "validatorDstAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $validator_dst_address = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $delegator_address
     *     @type string $validator_src_address
     *     @type string $validator_dst_address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Staking\V1Beta1\Staking::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string delegator_address = 1 [json_name = "delegatorAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getDelegatorAddress()
    {
        return $this->delegator_address;
    }

    /**
     * Generated from protobuf field <code>string delegator_address = 1 [json_name = "delegatorAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setDelegatorAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->delegator_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string validator_src_address = 2 [json_name = "validatorSrcAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getValidatorSrcAddress()
    {
        return $this->validator_src_address;
    }

    /**
     * Generated from protobuf field <code>string validator_src_address = 2 [json_name = "validatorSrcAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setValidatorSrcAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->validator_src_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string validator_dst_address = 3 [json_name = "validatorDstAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getValidatorDstAddress()
    {
        return $this->validator_dst_address;
    }

    /**
     * Generated from protobuf field <code>string validator_dst_address = 3 [json_name = "validatorDstAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setValidatorDstAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->validator_dst_address = $var;

        return $this;
    }

}

