<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/staking/v1beta1/genesis.proto

namespace Cosmos\Staking\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LastValidatorPower required for validator set update logic.
 *
 * Generated from protobuf message <code>cosmos.staking.v1beta1.LastValidatorPower</code>
 */
class LastValidatorPower extends \Google\Protobuf\Internal\Message
{
    /**
     * address is the address of the validator.
     *
     * Generated from protobuf field <code>string address = 1 [json_name = "address", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $address = '';
    /**
     * power defines the power of the validator.
     *
     * Generated from protobuf field <code>int64 power = 2 [json_name = "power"];</code>
     */
    protected $power = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *           address is the address of the validator.
     *     @type int|string $power
     *           power defines the power of the validator.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Staking\V1Beta1\Genesis::initOnce();
        parent::__construct($data);
    }

    /**
     * address is the address of the validator.
     *
     * Generated from protobuf field <code>string address = 1 [json_name = "address", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * address is the address of the validator.
     *
     * Generated from protobuf field <code>string address = 1 [json_name = "address", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * power defines the power of the validator.
     *
     * Generated from protobuf field <code>int64 power = 2 [json_name = "power"];</code>
     * @return int|string
     */
    public function getPower()
    {
        return $this->power;
    }

    /**
     * power defines the power of the validator.
     *
     * Generated from protobuf field <code>int64 power = 2 [json_name = "power"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setPower($var)
    {
        GPBUtil::checkInt64($var);
        $this->power = $var;

        return $this;
    }

}

