<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/staking/v1beta1/staking.proto

namespace Cosmos\Staking\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Pool is used for tracking bonded and not-bonded token supply of the bond
 * denomination.
 *
 * Generated from protobuf message <code>cosmos.staking.v1beta1.Pool</code>
 */
class Pool extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string not_bonded_tokens = 1 [json_name = "notBondedTokens", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.gogoproto.jsontag) = "not_bonded_tokens"];</code>
     */
    protected $not_bonded_tokens = '';
    /**
     * Generated from protobuf field <code>string bonded_tokens = 2 [json_name = "bondedTokens", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.gogoproto.jsontag) = "bonded_tokens", (.gogoproto.moretags) = "yaml:\"bonded_tokens\""];</code>
     */
    protected $bonded_tokens = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $not_bonded_tokens
     *     @type string $bonded_tokens
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Staking\V1beta1\GPBMetadata\Staking::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string not_bonded_tokens = 1 [json_name = "notBondedTokens", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.gogoproto.jsontag) = "not_bonded_tokens"];</code>
     * @return string
     */
    public function getNotBondedTokens()
    {
        return $this->not_bonded_tokens;
    }

    /**
     * Generated from protobuf field <code>string not_bonded_tokens = 1 [json_name = "notBondedTokens", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.gogoproto.jsontag) = "not_bonded_tokens"];</code>
     * @param string $var
     * @return $this
     */
    public function setNotBondedTokens($var)
    {
        GPBUtil::checkString($var, True);
        $this->not_bonded_tokens = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bonded_tokens = 2 [json_name = "bondedTokens", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.gogoproto.jsontag) = "bonded_tokens", (.gogoproto.moretags) = "yaml:\"bonded_tokens\""];</code>
     * @return string
     */
    public function getBondedTokens()
    {
        return $this->bonded_tokens;
    }

    /**
     * Generated from protobuf field <code>string bonded_tokens = 2 [json_name = "bondedTokens", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.gogoproto.jsontag) = "bonded_tokens", (.gogoproto.moretags) = "yaml:\"bonded_tokens\""];</code>
     * @param string $var
     * @return $this
     */
    public function setBondedTokens($var)
    {
        GPBUtil::checkString($var, True);
        $this->bonded_tokens = $var;

        return $this;
    }

}

