<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/staking/v1beta1/query.proto

namespace Cosmos\Staking\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryValidatorDelegationsRequest is request type for the
 * Query/ValidatorDelegations RPC method
 *
 * Generated from protobuf message <code>cosmos.staking.v1beta1.QueryValidatorDelegationsRequest</code>
 */
class QueryValidatorDelegationsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * validator_addr defines the validator address to query for.
     *
     * Generated from protobuf field <code>string validator_addr = 1 [json_name = "validatorAddr"];</code>
     */
    protected $validator_addr = '';
    /**
     * pagination defines an optional pagination for the request.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     */
    protected $pagination = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $validator_addr
     *           validator_addr defines the validator address to query for.
     *     @type \Cosmos\Base\Query\V1beta1\PageRequest $pagination
     *           pagination defines an optional pagination for the request.
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Staking\V1beta1\GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * validator_addr defines the validator address to query for.
     *
     * Generated from protobuf field <code>string validator_addr = 1 [json_name = "validatorAddr"];</code>
     * @return string
     */
    public function getValidatorAddr()
    {
        return $this->validator_addr;
    }

    /**
     * validator_addr defines the validator address to query for.
     *
     * Generated from protobuf field <code>string validator_addr = 1 [json_name = "validatorAddr"];</code>
     * @param string $var
     * @return $this
     */
    public function setValidatorAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->validator_addr = $var;

        return $this;
    }

    /**
     * pagination defines an optional pagination for the request.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     * @return \Cosmos\Base\Query\V1beta1\PageRequest|null
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    public function hasPagination()
    {
        return isset($this->pagination);
    }

    public function clearPagination()
    {
        unset($this->pagination);
    }

    /**
     * pagination defines an optional pagination for the request.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageRequest pagination = 2 [json_name = "pagination"];</code>
     * @param \Cosmos\Base\Query\V1beta1\PageRequest $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Base\Query\V1beta1\PageRequest::class);
        $this->pagination = $var;

        return $this;
    }

}

