<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/swap/v1/events.proto

namespace Decimal\Swap\V1\GPBMetadata;

class Events
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Gogoproto\GPBMetadata\Gogo::initOnce();
        \CosmosProto\GPBMetadata\Cosmos::initOnce();
        $pool->internalAddGeneratedFile(
            '
¨
decimal/swap/v1/events.protodecimal.swap.v1cosmos_proto/cosmos.proto"r
EventActivateChain0
sender (	BÒ´-cosmos.AddressStringRsender
id (BâÞIDRid
name (	Rname"`
EventDeactivateChain0
sender (	BÒ´-cosmos.AddressStringRsender
id (BâÞIDRid"ó
EventInitializeSwap
sender (	Rsender
	recipient (	R	recipient
amount (	Ramount!
token_symbol (	RtokenSymbol-
transaction_number (	RtransactionNumber

from_chain (R	fromChain

dest_chain (R	destChain"Î
EventRedeemSwap
sender (	Rsender
from (	Rfrom
	recipient (	R	recipient
amount (	Ramount!
token_symbol (	RtokenSymbol-
transaction_number (	RtransactionNumber

from_chain (R	fromChain

dest_chain (R	destChain
hash_redeem	 (	R
hashRedeem
v
 (	Rv
r (	Rr
s (	RsB¶
com.decimal.swap.v1BEventsProtoPZ4bitbucket.org/decimalteam/go-smart-node/x/swap/types¢DSXªDecimal.Swap.V1ÊDecimal\\Swap\\V1âDecimal\\Swap\\V1\\GPBMetadataêDecimal::Swap::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

