<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/nft/v1beta1/event.proto

namespace GPBMetadata\Cosmos\Nft\V1Beta1;

class Event
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
cosmos/nft/v1beta1/event.protocosmos.nft.v1beta1"j
	EventSend
class_id (	RclassId
id (	Rid
sender (	Rsender
receiver (	Rreceiver"L
	EventMint
class_id (	RclassId
id (	Rid
owner (	Rowner"L
	EventBurn
class_id (	RclassId
id (	Rid
owner (	RownerB$Z"github.com/cosmos/cosmos-sdk/x/nftbproto3'
        , true);

        static::$is_initialized = true;
    }
}

