<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/upgrade/v1beta1/tx.proto

namespace Cosmos\Upgrade\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgCancelUpgradeResponse is the Msg/CancelUpgrade response type.
 * Since: cosmos-sdk 0.46
 *
 * Generated from protobuf message <code>cosmos.upgrade.v1beta1.MsgCancelUpgradeResponse</code>
 */
class MsgCancelUpgradeResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Upgrade\V1Beta1\Tx::initOnce();
        parent::__construct($data);
    }

}

