<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/upgrade/v1beta1/query.proto

namespace Cosmos\Upgrade\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryCurrentPlanRequest is the request type for the Query/CurrentPlan RPC
 * method.
 *
 * Generated from protobuf message <code>cosmos.upgrade.v1beta1.QueryCurrentPlanRequest</code>
 */
class QueryCurrentPlanRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Upgrade\V1beta1\GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

}

