<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/validator/v1/events.proto

namespace GPBMetadata\Decimal\Validator\V1;

class Events
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
~
!decimal/validator/v1/events.protodecimal.validator.v1B;Z9bitbucket.org/decimalteam/go-smart-node/x/validator/typesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

