<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/lightclients/tendermint/v1/tendermint.proto

namespace Ibc\Lightclients\Tendermint\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ConsensusState defines the consensus state from Tendermint.
 *
 * Generated from protobuf message <code>ibc.lightclients.tendermint.v1.ConsensusState</code>
 */
class ConsensusState extends \Google\Protobuf\Internal\Message
{
    /**
     * timestamp that corresponds to the block height in which the ConsensusState
     * was stored.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1 [json_name = "timestamp", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    protected $timestamp = null;
    /**
     * commitment root (i.e app hash)
     *
     * Generated from protobuf field <code>.ibc.core.commitment.v1.MerkleRoot root = 2 [json_name = "root", (.gogoproto.nullable) = false];</code>
     */
    protected $root = null;
    /**
     * Generated from protobuf field <code>bytes next_validators_hash = 3 [json_name = "nextValidatorsHash", (.gogoproto.moretags) = "yaml:\"next_validators_hash\"", (.gogoproto.casttype) = "github.com/tendermint/tendermint/libs/bytes.HexBytes"];</code>
     */
    protected $next_validators_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $timestamp
     *           timestamp that corresponds to the block height in which the ConsensusState
     *           was stored.
     *     @type \Ibc\Core\Commitment\V1\MerkleRoot $root
     *           commitment root (i.e app hash)
     *     @type string $next_validators_hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Lightclients\Tendermint\V1\Tendermint::initOnce();
        parent::__construct($data);
    }

    /**
     * timestamp that corresponds to the block height in which the ConsensusState
     * was stored.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1 [json_name = "timestamp", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * timestamp that corresponds to the block height in which the ConsensusState
     * was stored.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1 [json_name = "timestamp", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * commitment root (i.e app hash)
     *
     * Generated from protobuf field <code>.ibc.core.commitment.v1.MerkleRoot root = 2 [json_name = "root", (.gogoproto.nullable) = false];</code>
     * @return \Ibc\Core\Commitment\V1\MerkleRoot|null
     */
    public function getRoot()
    {
        return $this->root;
    }

    public function hasRoot()
    {
        return isset($this->root);
    }

    public function clearRoot()
    {
        unset($this->root);
    }

    /**
     * commitment root (i.e app hash)
     *
     * Generated from protobuf field <code>.ibc.core.commitment.v1.MerkleRoot root = 2 [json_name = "root", (.gogoproto.nullable) = false];</code>
     * @param \Ibc\Core\Commitment\V1\MerkleRoot $var
     * @return $this
     */
    public function setRoot($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Core\Commitment\V1\MerkleRoot::class);
        $this->root = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes next_validators_hash = 3 [json_name = "nextValidatorsHash", (.gogoproto.moretags) = "yaml:\"next_validators_hash\"", (.gogoproto.casttype) = "github.com/tendermint/tendermint/libs/bytes.HexBytes"];</code>
     * @return string
     */
    public function getNextValidatorsHash()
    {
        return $this->next_validators_hash;
    }

    /**
     * Generated from protobuf field <code>bytes next_validators_hash = 3 [json_name = "nextValidatorsHash", (.gogoproto.moretags) = "yaml:\"next_validators_hash\"", (.gogoproto.casttype) = "github.com/tendermint/tendermint/libs/bytes.HexBytes"];</code>
     * @param string $var
     * @return $this
     */
    public function setNextValidatorsHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->next_validators_hash = $var;

        return $this;
    }

}

