<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/base/query/v1beta1/pagination.proto

namespace Cosmos\Base\Query\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PageResponse is to be embedded in gRPC response messages where the
 * corresponding request message has used PageRequest.
 *  message SomeResponse {
 *          repeated Bar results = 1;
 *          PageResponse page = 2;
 *  }
 *
 * Generated from protobuf message <code>cosmos.base.query.v1beta1.PageResponse</code>
 */
class PageResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * next_key is the key to be passed to PageRequest.key to
     * query the next page most efficiently. It will be empty if
     * there are no more results.
     *
     * Generated from protobuf field <code>bytes next_key = 1 [json_name = "nextKey"];</code>
     */
    protected $next_key = '';
    /**
     * total is total number of results available if PageRequest.count_total
     * was set, its value is undefined otherwise
     *
     * Generated from protobuf field <code>uint64 total = 2 [json_name = "total"];</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $next_key
     *           next_key is the key to be passed to PageRequest.key to
     *           query the next page most efficiently. It will be empty if
     *           there are no more results.
     *     @type int|string $total
     *           total is total number of results available if PageRequest.count_total
     *           was set, its value is undefined otherwise
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Base\Query\V1Beta1\Pagination::initOnce();
        parent::__construct($data);
    }

    /**
     * next_key is the key to be passed to PageRequest.key to
     * query the next page most efficiently. It will be empty if
     * there are no more results.
     *
     * Generated from protobuf field <code>bytes next_key = 1 [json_name = "nextKey"];</code>
     * @return string
     */
    public function getNextKey()
    {
        return $this->next_key;
    }

    /**
     * next_key is the key to be passed to PageRequest.key to
     * query the next page most efficiently. It will be empty if
     * there are no more results.
     *
     * Generated from protobuf field <code>bytes next_key = 1 [json_name = "nextKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setNextKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->next_key = $var;

        return $this;
    }

    /**
     * total is total number of results available if PageRequest.count_total
     * was set, its value is undefined otherwise
     *
     * Generated from protobuf field <code>uint64 total = 2 [json_name = "total"];</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * total is total number of results available if PageRequest.count_total
     * was set, its value is undefined otherwise
     *
     * Generated from protobuf field <code>uint64 total = 2 [json_name = "total"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint64($var);
        $this->total = $var;

        return $this;
    }

}

