<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/events.proto

namespace Cosmos\Group\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * EventCreateGroup is an event emitted when a group is created.
 *
 * Generated from protobuf message <code>cosmos.group.v1.EventCreateGroup</code>
 */
class EventCreateGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * group_id is the unique ID of the group.
     *
     * Generated from protobuf field <code>uint64 group_id = 1 [json_name = "groupId"];</code>
     */
    protected $group_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $group_id
     *           group_id is the unique ID of the group.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Group\V1\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * group_id is the unique ID of the group.
     *
     * Generated from protobuf field <code>uint64 group_id = 1 [json_name = "groupId"];</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * group_id is the unique ID of the group.
     *
     * Generated from protobuf field <code>uint64 group_id = 1 [json_name = "groupId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkUint64($var);
        $this->group_id = $var;

        return $this;
    }

}

