<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/tx.proto

namespace Cosmos\Group\V1;

use UnexpectedValueException;

/**
 * Exec defines modes of execution of a proposal on creation or on new vote.
 *
 * Protobuf type <code>cosmos.group.v1.Exec</code>
 */
class Exec
{
    /**
     * An empty value means that there should be a separate
     * MsgExec request for the proposal to execute.
     *
     * Generated from protobuf enum <code>EXEC_UNSPECIFIED = 0;</code>
     */
    const EXEC_UNSPECIFIED = 0;
    /**
     * Try to execute the proposal immediately.
     * If the proposal is not allowed per the DecisionPolicy,
     * the proposal will still be open and could
     * be executed at a later point.
     *
     * Generated from protobuf enum <code>EXEC_TRY = 1;</code>
     */
    const EXEC_TRY = 1;

    private static $valueToName = [
        self::EXEC_UNSPECIFIED => 'EXEC_UNSPECIFIED',
        self::EXEC_TRY => 'EXEC_TRY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

