<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/types.proto

namespace Cosmos\Group\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MemberRequest represents a group member to be used in Msg server requests.
 * Contrary to `Member`, it doesn't have any `added_at` field
 * since this field cannot be set as part of requests.
 *
 * Generated from protobuf message <code>cosmos.group.v1.MemberRequest</code>
 */
class MemberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * address is the member's account address.
     *
     * Generated from protobuf field <code>string address = 1 [json_name = "address", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $address = '';
    /**
     * weight is the member's voting weight that should be greater than 0.
     *
     * Generated from protobuf field <code>string weight = 2 [json_name = "weight"];</code>
     */
    protected $weight = '';
    /**
     * metadata is any arbitrary metadata attached to the member.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     */
    protected $metadata = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *           address is the member's account address.
     *     @type string $weight
     *           weight is the member's voting weight that should be greater than 0.
     *     @type string $metadata
     *           metadata is any arbitrary metadata attached to the member.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Group\V1\Types::initOnce();
        parent::__construct($data);
    }

    /**
     * address is the member's account address.
     *
     * Generated from protobuf field <code>string address = 1 [json_name = "address", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * address is the member's account address.
     *
     * Generated from protobuf field <code>string address = 1 [json_name = "address", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * weight is the member's voting weight that should be greater than 0.
     *
     * Generated from protobuf field <code>string weight = 2 [json_name = "weight"];</code>
     * @return string
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * weight is the member's voting weight that should be greater than 0.
     *
     * Generated from protobuf field <code>string weight = 2 [json_name = "weight"];</code>
     * @param string $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkString($var, True);
        $this->weight = $var;

        return $this;
    }

    /**
     * metadata is any arbitrary metadata attached to the member.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * metadata is any arbitrary metadata attached to the member.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->metadata = $var;

        return $this;
    }

}

