<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/tx.proto

namespace Cosmos\Group\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgCreateGroup is the Msg/CreateGroup request type.
 *
 * Generated from protobuf message <code>cosmos.group.v1.MsgCreateGroup</code>
 */
class MsgCreateGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $admin = '';
    /**
     * members defines the group members.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.MemberRequest members = 2 [json_name = "members", (.gogoproto.nullable) = false];</code>
     */
    private $members;
    /**
     * metadata is any arbitrary metadata to attached to the group.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     */
    protected $metadata = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $admin
     *           admin is the account address of the group admin.
     *     @type \Cosmos\Group\V1\MemberRequest[]|\Google\Protobuf\Internal\RepeatedField $members
     *           members defines the group members.
     *     @type string $metadata
     *           metadata is any arbitrary metadata to attached to the group.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Group\V1\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getAdmin()
    {
        return $this->admin;
    }

    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setAdmin($var)
    {
        GPBUtil::checkString($var, True);
        $this->admin = $var;

        return $this;
    }

    /**
     * members defines the group members.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.MemberRequest members = 2 [json_name = "members", (.gogoproto.nullable) = false];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * members defines the group members.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.MemberRequest members = 2 [json_name = "members", (.gogoproto.nullable) = false];</code>
     * @param \Cosmos\Group\V1\MemberRequest[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cosmos\Group\V1\MemberRequest::class);
        $this->members = $arr;

        return $this;
    }

    /**
     * metadata is any arbitrary metadata to attached to the group.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * metadata is any arbitrary metadata to attached to the group.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->metadata = $var;

        return $this;
    }

}

