<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/tx.proto

namespace Cosmos\Group\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgExec is the Msg/Exec request type.
 *
 * Generated from protobuf message <code>cosmos.group.v1.MsgExec</code>
 */
class MsgExec extends \Google\Protobuf\Internal\Message
{
    /**
     * proposal is the unique ID of the proposal.
     *
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId"];</code>
     */
    protected $proposal_id = 0;
    /**
     * executor is the account address used to execute the proposal.
     *
     * Generated from protobuf field <code>string executor = 2 [json_name = "executor", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $executor = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $proposal_id
     *           proposal is the unique ID of the proposal.
     *     @type string $executor
     *           executor is the account address used to execute the proposal.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Group\V1\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * proposal is the unique ID of the proposal.
     *
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId"];</code>
     * @return int|string
     */
    public function getProposalId()
    {
        return $this->proposal_id;
    }

    /**
     * proposal is the unique ID of the proposal.
     *
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setProposalId($var)
    {
        GPBUtil::checkUint64($var);
        $this->proposal_id = $var;

        return $this;
    }

    /**
     * executor is the account address used to execute the proposal.
     *
     * Generated from protobuf field <code>string executor = 2 [json_name = "executor", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getExecutor()
    {
        return $this->executor;
    }

    /**
     * executor is the account address used to execute the proposal.
     *
     * Generated from protobuf field <code>string executor = 2 [json_name = "executor", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setExecutor($var)
    {
        GPBUtil::checkString($var, True);
        $this->executor = $var;

        return $this;
    }

}

