<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/tx.proto

namespace Cosmos\Group\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgUpdateGroupPolicyMetadata is the Msg/UpdateGroupPolicyMetadata request type.
 *
 * Generated from protobuf message <code>cosmos.group.v1.MsgUpdateGroupPolicyMetadata</code>
 */
class MsgUpdateGroupPolicyMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $admin = '';
    /**
     * group_policy_address is the account address of group policy.
     *
     * Generated from protobuf field <code>string group_policy_address = 2 [json_name = "groupPolicyAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $group_policy_address = '';
    /**
     * metadata is the updated group policy metadata.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     */
    protected $metadata = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $admin
     *           admin is the account address of the group admin.
     *     @type string $group_policy_address
     *           group_policy_address is the account address of group policy.
     *     @type string $metadata
     *           metadata is the updated group policy metadata.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Group\V1\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getAdmin()
    {
        return $this->admin;
    }

    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setAdmin($var)
    {
        GPBUtil::checkString($var, True);
        $this->admin = $var;

        return $this;
    }

    /**
     * group_policy_address is the account address of group policy.
     *
     * Generated from protobuf field <code>string group_policy_address = 2 [json_name = "groupPolicyAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getGroupPolicyAddress()
    {
        return $this->group_policy_address;
    }

    /**
     * group_policy_address is the account address of group policy.
     *
     * Generated from protobuf field <code>string group_policy_address = 2 [json_name = "groupPolicyAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setGroupPolicyAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_policy_address = $var;

        return $this;
    }

    /**
     * metadata is the updated group policy metadata.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * metadata is the updated group policy metadata.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->metadata = $var;

        return $this;
    }

}

