<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/tx.proto

namespace Cosmos\Group\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgUpdateGroupMetadata is the Msg/UpdateGroupMetadata request type.
 *
 * Generated from protobuf message <code>cosmos.group.v1.MsgUpdateGroupMetadata</code>
 */
class MsgUpdateGroupMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $admin = '';
    /**
     * group_id is the unique ID of the group.
     *
     * Generated from protobuf field <code>uint64 group_id = 2 [json_name = "groupId"];</code>
     */
    protected $group_id = 0;
    /**
     * metadata is the updated group's metadata.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     */
    protected $metadata = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $admin
     *           admin is the account address of the group admin.
     *     @type int|string $group_id
     *           group_id is the unique ID of the group.
     *     @type string $metadata
     *           metadata is the updated group's metadata.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Group\V1\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getAdmin()
    {
        return $this->admin;
    }

    /**
     * admin is the account address of the group admin.
     *
     * Generated from protobuf field <code>string admin = 1 [json_name = "admin", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setAdmin($var)
    {
        GPBUtil::checkString($var, True);
        $this->admin = $var;

        return $this;
    }

    /**
     * group_id is the unique ID of the group.
     *
     * Generated from protobuf field <code>uint64 group_id = 2 [json_name = "groupId"];</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * group_id is the unique ID of the group.
     *
     * Generated from protobuf field <code>uint64 group_id = 2 [json_name = "groupId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkUint64($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * metadata is the updated group's metadata.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * metadata is the updated group's metadata.
     *
     * Generated from protobuf field <code>string metadata = 3 [json_name = "metadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->metadata = $var;

        return $this;
    }

}

