<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/query.proto

namespace Cosmos\Group\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryProposalsByGroupPolicyResponse is the Query/ProposalByGroupPolicy response type.
 *
 * Generated from protobuf message <code>cosmos.group.v1.QueryProposalsByGroupPolicyResponse</code>
 */
class QueryProposalsByGroupPolicyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * proposals are the proposals with given group policy.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.Proposal proposals = 1 [json_name = "proposals"];</code>
     */
    private $proposals;
    /**
     * pagination defines the pagination in the response.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     */
    protected $pagination = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cosmos\Group\V1\Proposal[]|\Google\Protobuf\Internal\RepeatedField $proposals
     *           proposals are the proposals with given group policy.
     *     @type \Cosmos\Base\Query\V1beta1\PageResponse $pagination
     *           pagination defines the pagination in the response.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Group\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * proposals are the proposals with given group policy.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.Proposal proposals = 1 [json_name = "proposals"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProposals()
    {
        return $this->proposals;
    }

    /**
     * proposals are the proposals with given group policy.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.Proposal proposals = 1 [json_name = "proposals"];</code>
     * @param \Cosmos\Group\V1\Proposal[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProposals($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cosmos\Group\V1\Proposal::class);
        $this->proposals = $arr;

        return $this;
    }

    /**
     * pagination defines the pagination in the response.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     * @return \Cosmos\Base\Query\V1beta1\PageResponse|null
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    public function hasPagination()
    {
        return isset($this->pagination);
    }

    public function clearPagination()
    {
        unset($this->pagination);
    }

    /**
     * pagination defines the pagination in the response.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     * @param \Cosmos\Base\Query\V1beta1\PageResponse $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Base\Query\V1beta1\PageResponse::class);
        $this->pagination = $var;

        return $this;
    }

}

