<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/group/v1/query.proto

namespace Cosmos\Group\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryGroupPoliciesByGroupResponse is the Query/GroupPoliciesByGroup response type.
 *
 * Generated from protobuf message <code>cosmos.group.v1.QueryGroupPoliciesByGroupResponse</code>
 */
class QueryGroupPoliciesByGroupResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * group_policies are the group policies info associated with the provided group.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.GroupPolicyInfo group_policies = 1 [json_name = "groupPolicies"];</code>
     */
    private $group_policies;
    /**
     * pagination defines the pagination in the response.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     */
    protected $pagination = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cosmos\Group\V1\GroupPolicyInfo[]|\Google\Protobuf\Internal\RepeatedField $group_policies
     *           group_policies are the group policies info associated with the provided group.
     *     @type \Cosmos\Base\Query\V1beta1\PageResponse $pagination
     *           pagination defines the pagination in the response.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Group\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * group_policies are the group policies info associated with the provided group.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.GroupPolicyInfo group_policies = 1 [json_name = "groupPolicies"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupPolicies()
    {
        return $this->group_policies;
    }

    /**
     * group_policies are the group policies info associated with the provided group.
     *
     * Generated from protobuf field <code>repeated .cosmos.group.v1.GroupPolicyInfo group_policies = 1 [json_name = "groupPolicies"];</code>
     * @param \Cosmos\Group\V1\GroupPolicyInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupPolicies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cosmos\Group\V1\GroupPolicyInfo::class);
        $this->group_policies = $arr;

        return $this;
    }

    /**
     * pagination defines the pagination in the response.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     * @return \Cosmos\Base\Query\V1beta1\PageResponse|null
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    public function hasPagination()
    {
        return isset($this->pagination);
    }

    public function clearPagination()
    {
        unset($this->pagination);
    }

    /**
     * pagination defines the pagination in the response.
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     * @param \Cosmos\Base\Query\V1beta1\PageResponse $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Base\Query\V1beta1\PageResponse::class);
        $this->pagination = $var;

        return $this;
    }

}

