<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/validator/v1/query.proto

namespace Decimal\Validator\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryDelegationsResponse is response type for the Query/Redelegations RPC method.
 *
 * Generated from protobuf message <code>decimal.validator.v1.QueryRedelegationsResponse</code>
 */
class QueryRedelegationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * redelegations defines the redelegations list for given delegator validator pair.
     *
     * Generated from protobuf field <code>repeated .decimal.validator.v1.Redelegation redelegations = 1 [json_name = "redelegations", (.gogoproto.nullable) = false];</code>
     */
    private $redelegations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Decimal\Validator\V1\Redelegation>|\Google\Protobuf\Internal\RepeatedField $redelegations
     *           redelegations defines the redelegations list for given delegator validator pair.
     * }
     */
    public function __construct($data = NULL) {
        \Decimal\Validator\V1\GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * redelegations defines the redelegations list for given delegator validator pair.
     *
     * Generated from protobuf field <code>repeated .decimal.validator.v1.Redelegation redelegations = 1 [json_name = "redelegations", (.gogoproto.nullable) = false];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRedelegations()
    {
        return $this->redelegations;
    }

    /**
     * redelegations defines the redelegations list for given delegator validator pair.
     *
     * Generated from protobuf field <code>repeated .decimal.validator.v1.Redelegation redelegations = 1 [json_name = "redelegations", (.gogoproto.nullable) = false];</code>
     * @param array<\Decimal\Validator\V1\Redelegation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRedelegations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Decimal\Validator\V1\Redelegation::class);
        $this->redelegations = $arr;

        return $this;
    }

}

