<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/validator/v1/query.proto

namespace Decimal\Validator\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryDelegationsResponse is response type for the Query/Undelegations RPC method.
 *
 * Generated from protobuf message <code>decimal.validator.v1.QueryUndelegationResponse</code>
 */
class QueryUndelegationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * undelegations defines the undelegation for given delegator validator pair.
     *
     * Generated from protobuf field <code>.decimal.validator.v1.Undelegation undelegation = 1 [json_name = "undelegation", (.gogoproto.nullable) = false];</code>
     */
    protected $undelegation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Decimal\Validator\V1\Undelegation $undelegation
     *           undelegations defines the undelegation for given delegator validator pair.
     * }
     */
    public function __construct($data = NULL) {
        \Decimal\Validator\V1\GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * undelegations defines the undelegation for given delegator validator pair.
     *
     * Generated from protobuf field <code>.decimal.validator.v1.Undelegation undelegation = 1 [json_name = "undelegation", (.gogoproto.nullable) = false];</code>
     * @return \Decimal\Validator\V1\Undelegation|null
     */
    public function getUndelegation()
    {
        return $this->undelegation;
    }

    public function hasUndelegation()
    {
        return isset($this->undelegation);
    }

    public function clearUndelegation()
    {
        unset($this->undelegation);
    }

    /**
     * undelegations defines the undelegation for given delegator validator pair.
     *
     * Generated from protobuf field <code>.decimal.validator.v1.Undelegation undelegation = 1 [json_name = "undelegation", (.gogoproto.nullable) = false];</code>
     * @param \Decimal\Validator\V1\Undelegation $var
     * @return $this
     */
    public function setUndelegation($var)
    {
        GPBUtil::checkMessage($var, \Decimal\Validator\V1\Undelegation::class);
        $this->undelegation = $var;

        return $this;
    }

}

