<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/validator/v1/query.proto

namespace Decimal\Validator\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryHistoricalInfoResponse is response type for the Query/HistoricalInfo RPC method.
 *
 * Generated from protobuf message <code>decimal.validator.v1.QueryHistoricalInfoResponse</code>
 */
class QueryHistoricalInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * hist defines the historical info at the given height.
     *
     * Generated from protobuf field <code>.decimal.validator.v1.HistoricalInfo hist = 1 [json_name = "hist"];</code>
     */
    protected $hist = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Decimal\Validator\V1\HistoricalInfo $hist
     *           hist defines the historical info at the given height.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Decimal\Validator\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * hist defines the historical info at the given height.
     *
     * Generated from protobuf field <code>.decimal.validator.v1.HistoricalInfo hist = 1 [json_name = "hist"];</code>
     * @return \Decimal\Validator\V1\HistoricalInfo|null
     */
    public function getHist()
    {
        return $this->hist;
    }

    public function hasHist()
    {
        return isset($this->hist);
    }

    public function clearHist()
    {
        unset($this->hist);
    }

    /**
     * hist defines the historical info at the given height.
     *
     * Generated from protobuf field <code>.decimal.validator.v1.HistoricalInfo hist = 1 [json_name = "hist"];</code>
     * @param \Decimal\Validator\V1\HistoricalInfo $var
     * @return $this
     */
    public function setHist($var)
    {
        GPBUtil::checkMessage($var, \Decimal\Validator\V1\HistoricalInfo::class);
        $this->hist = $var;

        return $this;
    }

}

