<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/validator/v1/events.proto

namespace Decimal\Validator\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SlashCoin contains coin slash info.
 *
 * Generated from protobuf message <code>decimal.validator.v1.SlashCoin</code>
 */
class SlashCoin extends \Google\Protobuf\Internal\Message
{
    /**
     * slash is the slashed coin.
     *
     * Generated from protobuf field <code>.cosmos.base.v1beta1.Coin slash = 1 [json_name = "slash", (.gogoproto.nullable) = false];</code>
     */
    protected $slash = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cosmos\Base\V1beta1\Coin $slash
     *           slash is the slashed coin.
     * }
     */
    public function __construct($data = NULL) {
        \Decimal\Validator\V1\GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * slash is the slashed coin.
     *
     * Generated from protobuf field <code>.cosmos.base.v1beta1.Coin slash = 1 [json_name = "slash", (.gogoproto.nullable) = false];</code>
     * @return \Cosmos\Base\V1beta1\Coin|null
     */
    public function getSlash()
    {
        return $this->slash;
    }

    public function hasSlash()
    {
        return isset($this->slash);
    }

    public function clearSlash()
    {
        unset($this->slash);
    }

    /**
     * slash is the slashed coin.
     *
     * Generated from protobuf field <code>.cosmos.base.v1beta1.Coin slash = 1 [json_name = "slash", (.gogoproto.nullable) = false];</code>
     * @param \Cosmos\Base\V1beta1\Coin $var
     * @return $this
     */
    public function setSlash($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Base\V1beta1\Coin::class);
        $this->slash = $var;

        return $this;
    }

}

