<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/nft/v1beta1/query.proto

namespace Cosmos\Nft\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryBalanceRequest is the request type for the Query/Balance RPC method
 *
 * Generated from protobuf message <code>cosmos.nft.v1beta1.QueryBalanceRequest</code>
 */
class QueryBalanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string class_id = 1 [json_name = "classId"];</code>
     */
    protected $class_id = '';
    /**
     * Generated from protobuf field <code>string owner = 2 [json_name = "owner"];</code>
     */
    protected $owner = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $class_id
     *     @type string $owner
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Nft\V1Beta1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string class_id = 1 [json_name = "classId"];</code>
     * @return string
     */
    public function getClassId()
    {
        return $this->class_id;
    }

    /**
     * Generated from protobuf field <code>string class_id = 1 [json_name = "classId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkString($var, True);
        $this->class_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner = 2 [json_name = "owner"];</code>
     * @return string
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Generated from protobuf field <code>string owner = 2 [json_name = "owner"];</code>
     * @param string $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;

        return $this;
    }

}

