<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gogoproto/gogo.proto

namespace Gogoproto\GPBMetadata;

class Gogo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ð
gogoproto/gogo.proto	gogoproto google/protobuf/descriptor.protoB‚
com.gogoprotoB	GogoProtoPZ"github.com/gogo/protobuf/gogoproto¢GXXª	GogoprotoÊ	GogoprotoâGogoproto\\GPBMetadataê	Gogoprotobproto3'
        , true);

        static::$is_initialized = true;
    }
}

