<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/crisis/v1beta1/tx.proto

namespace Cosmos\Crisis\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgVerifyInvariantResponse defines the Msg/VerifyInvariant response type.
 *
 * Generated from protobuf message <code>cosmos.crisis.v1beta1.MsgVerifyInvariantResponse</code>
 */
class MsgVerifyInvariantResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Crisis\V1beta1\GPBMetadata\Tx::initOnce();
        parent::__construct($data);
    }

}

