<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/multisig/v1/tx.proto

namespace Decimal\Multisig\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgCreateTransaction defines a SDK message for creating multisig transaction in existing wallet.
 *
 * Generated from protobuf message <code>decimal.multisig.v1.MsgCreateTransaction</code>
 */
class MsgCreateTransaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $sender = '';
    /**
     * Generated from protobuf field <code>string wallet = 2 [json_name = "wallet", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $wallet = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Any content = 3 [json_name = "content", (.cosmos_proto.accepts_interface) = "Content"];</code>
     */
    protected $content = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sender
     *     @type string $wallet
     *     @type \Google\Protobuf\Any $content
     * }
     */
    public function __construct($data = NULL) {
        \Decimal\Multisig\V1\GPBMetadata\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setSender($var)
    {
        GPBUtil::checkString($var, True);
        $this->sender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet = 2 [json_name = "wallet", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getWallet()
    {
        return $this->wallet;
    }

    /**
     * Generated from protobuf field <code>string wallet = 2 [json_name = "wallet", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setWallet($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any content = 3 [json_name = "content", (.cosmos_proto.accepts_interface) = "Content"];</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getContent()
    {
        return $this->content;
    }

    public function hasContent()
    {
        return isset($this->content);
    }

    public function clearContent()
    {
        unset($this->content);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any content = 3 [json_name = "content", (.cosmos_proto.accepts_interface) = "Content"];</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->content = $var;

        return $this;
    }

}

