<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/bank/v1beta1/query.proto

namespace Cosmos\Bank\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryBalanceResponse is the response type for the Query/Balance RPC method.
 *
 * Generated from protobuf message <code>cosmos.bank.v1beta1.QueryBalanceResponse</code>
 */
class QueryBalanceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * balance is the balance of the coin.
     *
     * Generated from protobuf field <code>.cosmos.base.v1beta1.Coin balance = 1 [json_name = "balance"];</code>
     */
    protected $balance = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cosmos\Base\V1beta1\Coin $balance
     *           balance is the balance of the coin.
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Bank\V1beta1\GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * balance is the balance of the coin.
     *
     * Generated from protobuf field <code>.cosmos.base.v1beta1.Coin balance = 1 [json_name = "balance"];</code>
     * @return \Cosmos\Base\V1beta1\Coin|null
     */
    public function getBalance()
    {
        return $this->balance;
    }

    public function hasBalance()
    {
        return isset($this->balance);
    }

    public function clearBalance()
    {
        unset($this->balance);
    }

    /**
     * balance is the balance of the coin.
     *
     * Generated from protobuf field <code>.cosmos.base.v1beta1.Coin balance = 1 [json_name = "balance"];</code>
     * @param \Cosmos\Base\V1beta1\Coin $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Base\V1beta1\Coin::class);
        $this->balance = $var;

        return $this;
    }

}

