<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proofs.proto

namespace Ics23;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Use BatchEntry not CommitmentProof, to avoid recursion
 *
 * Generated from protobuf message <code>ics23.BatchEntry</code>
 */
class BatchEntry extends \Google\Protobuf\Internal\Message
{
    protected $proof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ics23\ExistenceProof $exist
     *     @type \Ics23\NonExistenceProof $nonexist
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proofs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ics23.ExistenceProof exist = 1 [json_name = "exist"];</code>
     * @return \Ics23\ExistenceProof|null
     */
    public function getExist()
    {
        return $this->readOneof(1);
    }

    public function hasExist()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.ics23.ExistenceProof exist = 1 [json_name = "exist"];</code>
     * @param \Ics23\ExistenceProof $var
     * @return $this
     */
    public function setExist($var)
    {
        GPBUtil::checkMessage($var, \Ics23\ExistenceProof::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ics23.NonExistenceProof nonexist = 2 [json_name = "nonexist"];</code>
     * @return \Ics23\NonExistenceProof|null
     */
    public function getNonexist()
    {
        return $this->readOneof(2);
    }

    public function hasNonexist()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.ics23.NonExistenceProof nonexist = 2 [json_name = "nonexist"];</code>
     * @param \Ics23\NonExistenceProof $var
     * @return $this
     */
    public function setNonexist($var)
    {
        GPBUtil::checkMessage($var, \Ics23\NonExistenceProof::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getProof()
    {
        return $this->whichOneof("proof");
    }

}

