<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proofs.proto

namespace Ics23;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ics23.CompressedExistenceProof</code>
 */
class CompressedExistenceProof extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes key = 1 [json_name = "key"];</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
     */
    protected $leaf = null;
    /**
     * these are indexes into the lookup_inners table in CompressedBatchProof
     *
     * Generated from protobuf field <code>repeated int32 path = 4 [json_name = "path"];</code>
     */
    private $path;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $value
     *     @type \Ics23\LeafOp $leaf
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $path
     *           these are indexes into the lookup_inners table in CompressedBatchProof
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proofs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes key = 1 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 1 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
     * @return \Ics23\LeafOp|null
     */
    public function getLeaf()
    {
        return $this->leaf;
    }

    public function hasLeaf()
    {
        return isset($this->leaf);
    }

    public function clearLeaf()
    {
        unset($this->leaf);
    }

    /**
     * Generated from protobuf field <code>.ics23.LeafOp leaf = 3 [json_name = "leaf"];</code>
     * @param \Ics23\LeafOp $var
     * @return $this
     */
    public function setLeaf($var)
    {
        GPBUtil::checkMessage($var, \Ics23\LeafOp::class);
        $this->leaf = $var;

        return $this;
    }

    /**
     * these are indexes into the lookup_inners table in CompressedBatchProof
     *
     * Generated from protobuf field <code>repeated int32 path = 4 [json_name = "path"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * these are indexes into the lookup_inners table in CompressedBatchProof
     *
     * Generated from protobuf field <code>repeated int32 path = 4 [json_name = "path"];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPath($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->path = $arr;

        return $this;
    }

}

