<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gogoproto/gogo.proto

namespace GPBMetadata\Gogoproto;

class Gogo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
’
gogoproto/gogo.proto	gogoproto google/protobuf/descriptor.protoBE
com.google.protobufB
GoGoProtosZ"github.com/gogo/protobuf/gogoprotobproto3'
        , true);

        static::$is_initialized = true;
    }
}

