<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/mint/v1beta1/mint.proto

namespace Cosmos\Mint\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Params holds parameters for the mint module.
 *
 * Generated from protobuf message <code>cosmos.mint.v1beta1.Params</code>
 */
class Params extends \Google\Protobuf\Internal\Message
{
    /**
     * type of coin to mint
     *
     * Generated from protobuf field <code>string mint_denom = 1 [json_name = "mintDenom"];</code>
     */
    protected $mint_denom = '';
    /**
     * maximum annual change in inflation rate
     *
     * Generated from protobuf field <code>string inflation_rate_change = 2 [json_name = "inflationRateChange", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     */
    protected $inflation_rate_change = '';
    /**
     * maximum inflation rate
     *
     * Generated from protobuf field <code>string inflation_max = 3 [json_name = "inflationMax", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     */
    protected $inflation_max = '';
    /**
     * minimum inflation rate
     *
     * Generated from protobuf field <code>string inflation_min = 4 [json_name = "inflationMin", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     */
    protected $inflation_min = '';
    /**
     * goal of percent bonded atoms
     *
     * Generated from protobuf field <code>string goal_bonded = 5 [json_name = "goalBonded", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     */
    protected $goal_bonded = '';
    /**
     * expected blocks per year
     *
     * Generated from protobuf field <code>uint64 blocks_per_year = 6 [json_name = "blocksPerYear"];</code>
     */
    protected $blocks_per_year = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mint_denom
     *           type of coin to mint
     *     @type string $inflation_rate_change
     *           maximum annual change in inflation rate
     *     @type string $inflation_max
     *           maximum inflation rate
     *     @type string $inflation_min
     *           minimum inflation rate
     *     @type string $goal_bonded
     *           goal of percent bonded atoms
     *     @type int|string $blocks_per_year
     *           expected blocks per year
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Mint\V1Beta1\Mint::initOnce();
        parent::__construct($data);
    }

    /**
     * type of coin to mint
     *
     * Generated from protobuf field <code>string mint_denom = 1 [json_name = "mintDenom"];</code>
     * @return string
     */
    public function getMintDenom()
    {
        return $this->mint_denom;
    }

    /**
     * type of coin to mint
     *
     * Generated from protobuf field <code>string mint_denom = 1 [json_name = "mintDenom"];</code>
     * @param string $var
     * @return $this
     */
    public function setMintDenom($var)
    {
        GPBUtil::checkString($var, True);
        $this->mint_denom = $var;

        return $this;
    }

    /**
     * maximum annual change in inflation rate
     *
     * Generated from protobuf field <code>string inflation_rate_change = 2 [json_name = "inflationRateChange", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     * @return string
     */
    public function getInflationRateChange()
    {
        return $this->inflation_rate_change;
    }

    /**
     * maximum annual change in inflation rate
     *
     * Generated from protobuf field <code>string inflation_rate_change = 2 [json_name = "inflationRateChange", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     * @param string $var
     * @return $this
     */
    public function setInflationRateChange($var)
    {
        GPBUtil::checkString($var, True);
        $this->inflation_rate_change = $var;

        return $this;
    }

    /**
     * maximum inflation rate
     *
     * Generated from protobuf field <code>string inflation_max = 3 [json_name = "inflationMax", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     * @return string
     */
    public function getInflationMax()
    {
        return $this->inflation_max;
    }

    /**
     * maximum inflation rate
     *
     * Generated from protobuf field <code>string inflation_max = 3 [json_name = "inflationMax", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     * @param string $var
     * @return $this
     */
    public function setInflationMax($var)
    {
        GPBUtil::checkString($var, True);
        $this->inflation_max = $var;

        return $this;
    }

    /**
     * minimum inflation rate
     *
     * Generated from protobuf field <code>string inflation_min = 4 [json_name = "inflationMin", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     * @return string
     */
    public function getInflationMin()
    {
        return $this->inflation_min;
    }

    /**
     * minimum inflation rate
     *
     * Generated from protobuf field <code>string inflation_min = 4 [json_name = "inflationMin", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     * @param string $var
     * @return $this
     */
    public function setInflationMin($var)
    {
        GPBUtil::checkString($var, True);
        $this->inflation_min = $var;

        return $this;
    }

    /**
     * goal of percent bonded atoms
     *
     * Generated from protobuf field <code>string goal_bonded = 5 [json_name = "goalBonded", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     * @return string
     */
    public function getGoalBonded()
    {
        return $this->goal_bonded;
    }

    /**
     * goal of percent bonded atoms
     *
     * Generated from protobuf field <code>string goal_bonded = 5 [json_name = "goalBonded", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.cosmos_proto.scalar) = "cosmos.Dec"];</code>
     * @param string $var
     * @return $this
     */
    public function setGoalBonded($var)
    {
        GPBUtil::checkString($var, True);
        $this->goal_bonded = $var;

        return $this;
    }

    /**
     * expected blocks per year
     *
     * Generated from protobuf field <code>uint64 blocks_per_year = 6 [json_name = "blocksPerYear"];</code>
     * @return int|string
     */
    public function getBlocksPerYear()
    {
        return $this->blocks_per_year;
    }

    /**
     * expected blocks per year
     *
     * Generated from protobuf field <code>uint64 blocks_per_year = 6 [json_name = "blocksPerYear"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlocksPerYear($var)
    {
        GPBUtil::checkUint64($var);
        $this->blocks_per_year = $var;

        return $this;
    }

}

