<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/mint/v1beta1/query.proto

namespace Cosmos\Mint\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryParamsRequest is the request type for the Query/Params RPC method.
 *
 * Generated from protobuf message <code>cosmos.mint.v1beta1.QueryParamsRequest</code>
 */
class QueryParamsRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Mint\V1beta1\GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

}

