<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/base/store/v1beta1/snapshot.proto

namespace Cosmos\Base\Store\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SnapshotIAVLItem is an exported IAVL node.
 *
 * Generated from protobuf message <code>cosmos.base.store.v1beta1.SnapshotIAVLItem</code>
 */
class SnapshotIAVLItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes key = 1 [json_name = "key"];</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>int64 version = 3 [json_name = "version"];</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>int32 height = 4 [json_name = "height"];</code>
     */
    protected $height = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $value
     *     @type int|string $version
     *     @type int $height
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Base\Store\V1beta1\GPBMetadata\Snapshot::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes key = 1 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 1 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 version = 3 [json_name = "version"];</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int64 version = 3 [json_name = "version"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 4 [json_name = "height"];</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int32 height = 4 [json_name = "height"];</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

}

