<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/gov/v1/tx.proto

namespace Cosmos\Gov\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgDepositResponse defines the Msg/Deposit response type.
 *
 * Generated from protobuf message <code>cosmos.gov.v1.MsgDepositResponse</code>
 */
class MsgDepositResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Gov\V1\Tx::initOnce();
        parent::__construct($data);
    }

}

