<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/gov/v1/tx.proto

namespace Cosmos\Gov\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgVote defines a message to cast a vote.
 *
 * Generated from protobuf message <code>cosmos.gov.v1.MsgVote</code>
 */
class MsgVote extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId", (.gogoproto.jsontag) = "proposal_id"];</code>
     */
    protected $proposal_id = 0;
    /**
     * Generated from protobuf field <code>string voter = 2 [json_name = "voter", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $voter = '';
    /**
     * Generated from protobuf field <code>.cosmos.gov.v1.VoteOption option = 3 [json_name = "option"];</code>
     */
    protected $option = 0;
    /**
     * Generated from protobuf field <code>string metadata = 4 [json_name = "metadata"];</code>
     */
    protected $metadata = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $proposal_id
     *     @type string $voter
     *     @type int $option
     *     @type string $metadata
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Gov\V1\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId", (.gogoproto.jsontag) = "proposal_id"];</code>
     * @return int|string
     */
    public function getProposalId()
    {
        return $this->proposal_id;
    }

    /**
     * Generated from protobuf field <code>uint64 proposal_id = 1 [json_name = "proposalId", (.gogoproto.jsontag) = "proposal_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setProposalId($var)
    {
        GPBUtil::checkUint64($var);
        $this->proposal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string voter = 2 [json_name = "voter", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getVoter()
    {
        return $this->voter;
    }

    /**
     * Generated from protobuf field <code>string voter = 2 [json_name = "voter", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setVoter($var)
    {
        GPBUtil::checkString($var, True);
        $this->voter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cosmos.gov.v1.VoteOption option = 3 [json_name = "option"];</code>
     * @return int
     */
    public function getOption()
    {
        return $this->option;
    }

    /**
     * Generated from protobuf field <code>.cosmos.gov.v1.VoteOption option = 3 [json_name = "option"];</code>
     * @param int $var
     * @return $this
     */
    public function setOption($var)
    {
        GPBUtil::checkEnum($var, \Cosmos\Gov\V1\VoteOption::class);
        $this->option = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string metadata = 4 [json_name = "metadata"];</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>string metadata = 4 [json_name = "metadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->metadata = $var;

        return $this;
    }

}

