<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/gov/v1/gov.proto

namespace Cosmos\Gov\V1;

use UnexpectedValueException;

/**
 * ProposalStatus enumerates the valid statuses of a proposal.
 *
 * Protobuf type <code>cosmos.gov.v1.ProposalStatus</code>
 */
class ProposalStatus
{
    /**
     * PROPOSAL_STATUS_UNSPECIFIED defines the default proposal status.
     *
     * Generated from protobuf enum <code>PROPOSAL_STATUS_UNSPECIFIED = 0;</code>
     */
    const PROPOSAL_STATUS_UNSPECIFIED = 0;
    /**
     * PROPOSAL_STATUS_DEPOSIT_PERIOD defines a proposal status during the deposit
     * period.
     *
     * Generated from protobuf enum <code>PROPOSAL_STATUS_DEPOSIT_PERIOD = 1;</code>
     */
    const PROPOSAL_STATUS_DEPOSIT_PERIOD = 1;
    /**
     * PROPOSAL_STATUS_VOTING_PERIOD defines a proposal status during the voting
     * period.
     *
     * Generated from protobuf enum <code>PROPOSAL_STATUS_VOTING_PERIOD = 2;</code>
     */
    const PROPOSAL_STATUS_VOTING_PERIOD = 2;
    /**
     * PROPOSAL_STATUS_PASSED defines a proposal status of a proposal that has
     * passed.
     *
     * Generated from protobuf enum <code>PROPOSAL_STATUS_PASSED = 3;</code>
     */
    const PROPOSAL_STATUS_PASSED = 3;
    /**
     * PROPOSAL_STATUS_REJECTED defines a proposal status of a proposal that has
     * been rejected.
     *
     * Generated from protobuf enum <code>PROPOSAL_STATUS_REJECTED = 4;</code>
     */
    const PROPOSAL_STATUS_REJECTED = 4;
    /**
     * PROPOSAL_STATUS_FAILED defines a proposal status of a proposal that has
     * failed.
     *
     * Generated from protobuf enum <code>PROPOSAL_STATUS_FAILED = 5;</code>
     */
    const PROPOSAL_STATUS_FAILED = 5;

    private static $valueToName = [
        self::PROPOSAL_STATUS_UNSPECIFIED => 'PROPOSAL_STATUS_UNSPECIFIED',
        self::PROPOSAL_STATUS_DEPOSIT_PERIOD => 'PROPOSAL_STATUS_DEPOSIT_PERIOD',
        self::PROPOSAL_STATUS_VOTING_PERIOD => 'PROPOSAL_STATUS_VOTING_PERIOD',
        self::PROPOSAL_STATUS_PASSED => 'PROPOSAL_STATUS_PASSED',
        self::PROPOSAL_STATUS_REJECTED => 'PROPOSAL_STATUS_REJECTED',
        self::PROPOSAL_STATUS_FAILED => 'PROPOSAL_STATUS_FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

