<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/vesting/v1beta1/tx.proto

namespace Cosmos\Vesting\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgCreatePermanentLockedAccountResponse defines the Msg/CreatePermanentLockedAccount response type.
 * Since: cosmos-sdk 0.46
 *
 * Generated from protobuf message <code>cosmos.vesting.v1beta1.MsgCreatePermanentLockedAccountResponse</code>
 */
class MsgCreatePermanentLockedAccountResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Vesting\V1Beta1\Tx::initOnce();
        parent::__construct($data);
    }

}

