<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/vesting/v1beta1/vesting.proto

namespace Cosmos\Vesting\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * PermanentLockedAccount implements the VestingAccount interface. It does
 * not ever release coins, locking them indefinitely. Coins in this account can
 * still be used for delegating and for governance votes even while locked.
 * Since: cosmos-sdk 0.43
 *
 * Generated from protobuf message <code>cosmos.vesting.v1beta1.PermanentLockedAccount</code>
 */
class PermanentLockedAccount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cosmos.vesting.v1beta1.BaseVestingAccount base_vesting_account = 1 [json_name = "baseVestingAccount", (.gogoproto.embed) = true];</code>
     */
    protected $base_vesting_account = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cosmos\Vesting\V1beta1\BaseVestingAccount $base_vesting_account
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Vesting\V1Beta1\Vesting::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cosmos.vesting.v1beta1.BaseVestingAccount base_vesting_account = 1 [json_name = "baseVestingAccount", (.gogoproto.embed) = true];</code>
     * @return \Cosmos\Vesting\V1beta1\BaseVestingAccount|null
     */
    public function getBaseVestingAccount()
    {
        return $this->base_vesting_account;
    }

    public function hasBaseVestingAccount()
    {
        return isset($this->base_vesting_account);
    }

    public function clearBaseVestingAccount()
    {
        unset($this->base_vesting_account);
    }

    /**
     * Generated from protobuf field <code>.cosmos.vesting.v1beta1.BaseVestingAccount base_vesting_account = 1 [json_name = "baseVestingAccount", (.gogoproto.embed) = true];</code>
     * @param \Cosmos\Vesting\V1beta1\BaseVestingAccount $var
     * @return $this
     */
    public function setBaseVestingAccount($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Vesting\V1beta1\BaseVestingAccount::class);
        $this->base_vesting_account = $var;

        return $this;
    }

}

