<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/distribution/v1beta1/genesis.proto

namespace Cosmos\Distribution\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ValidatorAccumulatedCommissionRecord is used for import / export via genesis
 * json.
 *
 * Generated from protobuf message <code>cosmos.distribution.v1beta1.ValidatorAccumulatedCommissionRecord</code>
 */
class ValidatorAccumulatedCommissionRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * validator_address is the address of the validator.
     *
     * Generated from protobuf field <code>string validator_address = 1 [json_name = "validatorAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $validator_address = '';
    /**
     * accumulated is the accumulated commission of a validator.
     *
     * Generated from protobuf field <code>.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission accumulated = 2 [json_name = "accumulated", (.gogoproto.nullable) = false];</code>
     */
    protected $accumulated = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $validator_address
     *           validator_address is the address of the validator.
     *     @type \Cosmos\Distribution\V1beta1\ValidatorAccumulatedCommission $accumulated
     *           accumulated is the accumulated commission of a validator.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Distribution\V1Beta1\Genesis::initOnce();
        parent::__construct($data);
    }

    /**
     * validator_address is the address of the validator.
     *
     * Generated from protobuf field <code>string validator_address = 1 [json_name = "validatorAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getValidatorAddress()
    {
        return $this->validator_address;
    }

    /**
     * validator_address is the address of the validator.
     *
     * Generated from protobuf field <code>string validator_address = 1 [json_name = "validatorAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setValidatorAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->validator_address = $var;

        return $this;
    }

    /**
     * accumulated is the accumulated commission of a validator.
     *
     * Generated from protobuf field <code>.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission accumulated = 2 [json_name = "accumulated", (.gogoproto.nullable) = false];</code>
     * @return \Cosmos\Distribution\V1beta1\ValidatorAccumulatedCommission|null
     */
    public function getAccumulated()
    {
        return $this->accumulated;
    }

    public function hasAccumulated()
    {
        return isset($this->accumulated);
    }

    public function clearAccumulated()
    {
        unset($this->accumulated);
    }

    /**
     * accumulated is the accumulated commission of a validator.
     *
     * Generated from protobuf field <code>.cosmos.distribution.v1beta1.ValidatorAccumulatedCommission accumulated = 2 [json_name = "accumulated", (.gogoproto.nullable) = false];</code>
     * @param \Cosmos\Distribution\V1beta1\ValidatorAccumulatedCommission $var
     * @return $this
     */
    public function setAccumulated($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Distribution\V1beta1\ValidatorAccumulatedCommission::class);
        $this->accumulated = $var;

        return $this;
    }

}

