<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/distribution/v1beta1/distribution.proto

namespace Cosmos\Distribution\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ValidatorSlashEvent represents a validator slash event.
 * Height is implicit within the store key.
 * This is needed to calculate appropriate amount of staking tokens
 * for delegations which are withdrawn after a slash has occurred.
 *
 * Generated from protobuf message <code>cosmos.distribution.v1beta1.ValidatorSlashEvent</code>
 */
class ValidatorSlashEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 validator_period = 1 [json_name = "validatorPeriod", (.gogoproto.moretags) = "yaml:\"validator_period\""];</code>
     */
    protected $validator_period = 0;
    /**
     * Generated from protobuf field <code>string fraction = 2 [json_name = "fraction", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    protected $fraction = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $validator_period
     *     @type string $fraction
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Distribution\V1beta1\GPBMetadata\Distribution::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 validator_period = 1 [json_name = "validatorPeriod", (.gogoproto.moretags) = "yaml:\"validator_period\""];</code>
     * @return int|string
     */
    public function getValidatorPeriod()
    {
        return $this->validator_period;
    }

    /**
     * Generated from protobuf field <code>uint64 validator_period = 1 [json_name = "validatorPeriod", (.gogoproto.moretags) = "yaml:\"validator_period\""];</code>
     * @param int|string $var
     * @return $this
     */
    public function setValidatorPeriod($var)
    {
        GPBUtil::checkUint64($var);
        $this->validator_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fraction = 2 [json_name = "fraction", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     * @return string
     */
    public function getFraction()
    {
        return $this->fraction;
    }

    /**
     * Generated from protobuf field <code>string fraction = 2 [json_name = "fraction", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     * @param string $var
     * @return $this
     */
    public function setFraction($var)
    {
        GPBUtil::checkString($var, True);
        $this->fraction = $var;

        return $this;
    }

}

