<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/coin/v1/events.proto

namespace Decimal\Coin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * EventUpdateCoinVR defines event emitted when volume or reserve of existing coin is updated.
 *
 * Generated from protobuf message <code>decimal.coin.v1.EventUpdateCoinVR</code>
 */
class EventUpdateCoinVR extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string denom = 1 [json_name = "denom"];</code>
     */
    protected $denom = '';
    /**
     * Generated from protobuf field <code>string volume = 2 [json_name = "volume"];</code>
     */
    protected $volume = '';
    /**
     * Generated from protobuf field <code>string reserve = 3 [json_name = "reserve"];</code>
     */
    protected $reserve = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $denom
     *     @type string $volume
     *     @type string $reserve
     * }
     */
    public function __construct($data = NULL) {
        \Decimal\Coin\V1\GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string denom = 1 [json_name = "denom"];</code>
     * @return string
     */
    public function getDenom()
    {
        return $this->denom;
    }

    /**
     * Generated from protobuf field <code>string denom = 1 [json_name = "denom"];</code>
     * @param string $var
     * @return $this
     */
    public function setDenom($var)
    {
        GPBUtil::checkString($var, True);
        $this->denom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string volume = 2 [json_name = "volume"];</code>
     * @return string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>string volume = 2 [json_name = "volume"];</code>
     * @param string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkString($var, True);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reserve = 3 [json_name = "reserve"];</code>
     * @return string
     */
    public function getReserve()
    {
        return $this->reserve;
    }

    /**
     * Generated from protobuf field <code>string reserve = 3 [json_name = "reserve"];</code>
     * @param string $var
     * @return $this
     */
    public function setReserve($var)
    {
        GPBUtil::checkString($var, True);
        $this->reserve = $var;

        return $this;
    }

}

