<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/coin/v1/tx.proto

namespace Decimal\Coin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgRedeemCheck defines a SDK message for redeeming a check.
 *
 * Generated from protobuf message <code>decimal.coin.v1.MsgRedeemCheck</code>
 */
class MsgRedeemCheck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     */
    protected $sender = '';
    /**
     * Generated from protobuf field <code>string check = 2 [json_name = "check"];</code>
     */
    protected $check = '';
    /**
     * Generated from protobuf field <code>string proof = 3 [json_name = "proof"];</code>
     */
    protected $proof = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sender
     *     @type string $check
     *     @type string $proof
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Decimal\Coin\V1\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return string
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * Generated from protobuf field <code>string sender = 1 [json_name = "sender", (.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @param string $var
     * @return $this
     */
    public function setSender($var)
    {
        GPBUtil::checkString($var, True);
        $this->sender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string check = 2 [json_name = "check"];</code>
     * @return string
     */
    public function getCheck()
    {
        return $this->check;
    }

    /**
     * Generated from protobuf field <code>string check = 2 [json_name = "check"];</code>
     * @param string $var
     * @return $this
     */
    public function setCheck($var)
    {
        GPBUtil::checkString($var, True);
        $this->check = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string proof = 3 [json_name = "proof"];</code>
     * @return string
     */
    public function getProof()
    {
        return $this->proof;
    }

    /**
     * Generated from protobuf field <code>string proof = 3 [json_name = "proof"];</code>
     * @param string $var
     * @return $this
     */
    public function setProof($var)
    {
        GPBUtil::checkString($var, True);
        $this->proof = $var;

        return $this;
    }

}

