<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decimal/coin/v1/query.proto

namespace Decimal\Coin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryChecksResponse is response type for the Query/Checks RPC method.
 *
 * Generated from protobuf message <code>decimal.coin.v1.QueryChecksResponse</code>
 */
class QueryChecksResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .decimal.coin.v1.Check checks = 1 [json_name = "checks", (.gogoproto.nullable) = false];</code>
     */
    private $checks;
    /**
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     */
    protected $pagination = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Decimal\Coin\V1\Check[]|\Google\Protobuf\Internal\RepeatedField $checks
     *     @type \Cosmos\Base\Query\V1beta1\PageResponse $pagination
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Decimal\Coin\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .decimal.coin.v1.Check checks = 1 [json_name = "checks", (.gogoproto.nullable) = false];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChecks()
    {
        return $this->checks;
    }

    /**
     * Generated from protobuf field <code>repeated .decimal.coin.v1.Check checks = 1 [json_name = "checks", (.gogoproto.nullable) = false];</code>
     * @param \Decimal\Coin\V1\Check[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChecks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Decimal\Coin\V1\Check::class);
        $this->checks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     * @return \Cosmos\Base\Query\V1beta1\PageResponse|null
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    public function hasPagination()
    {
        return isset($this->pagination);
    }

    public function clearPagination()
    {
        unset($this->pagination);
    }

    /**
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];</code>
     * @param \Cosmos\Base\Query\V1beta1\PageResponse $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Base\Query\V1beta1\PageResponse::class);
        $this->pagination = $var;

        return $this;
    }

}

