<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/fee/v1/query.proto

namespace Ibc\Applications\Fee\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryIncentivizedPacketsResponse defines the response type for the IncentivizedPacket rpc
 *
 * Generated from protobuf message <code>ibc.applications.fee.v1.QueryIncentivizedPacketResponse</code>
 */
class QueryIncentivizedPacketResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * the identified fees for the incentivized packet
     *
     * Generated from protobuf field <code>.ibc.applications.fee.v1.IdentifiedPacketFees incentivized_packet = 1 [json_name = "incentivizedPacket", (.gogoproto.nullable) = false];</code>
     */
    protected $incentivized_packet = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ibc\Applications\Fee\V1\IdentifiedPacketFees $incentivized_packet
     *           the identified fees for the incentivized packet
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Applications\Fee\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * the identified fees for the incentivized packet
     *
     * Generated from protobuf field <code>.ibc.applications.fee.v1.IdentifiedPacketFees incentivized_packet = 1 [json_name = "incentivizedPacket", (.gogoproto.nullable) = false];</code>
     * @return \Ibc\Applications\Fee\V1\IdentifiedPacketFees|null
     */
    public function getIncentivizedPacket()
    {
        return $this->incentivized_packet;
    }

    public function hasIncentivizedPacket()
    {
        return isset($this->incentivized_packet);
    }

    public function clearIncentivizedPacket()
    {
        unset($this->incentivized_packet);
    }

    /**
     * the identified fees for the incentivized packet
     *
     * Generated from protobuf field <code>.ibc.applications.fee.v1.IdentifiedPacketFees incentivized_packet = 1 [json_name = "incentivizedPacket", (.gogoproto.nullable) = false];</code>
     * @param \Ibc\Applications\Fee\V1\IdentifiedPacketFees $var
     * @return $this
     */
    public function setIncentivizedPacket($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Applications\Fee\V1\IdentifiedPacketFees::class);
        $this->incentivized_packet = $var;

        return $this;
    }

}

