<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/channel/v1/tx.proto

namespace Ibc\Core\Channel\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgRecvPacket receives incoming IBC packet
 *
 * Generated from protobuf message <code>ibc.core.channel.v1.MsgRecvPacket</code>
 */
class MsgRecvPacket extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ibc.core.channel.v1.Packet packet = 1 [json_name = "packet", (.gogoproto.nullable) = false];</code>
     */
    protected $packet = null;
    /**
     * Generated from protobuf field <code>bytes proof_commitment = 2 [json_name = "proofCommitment", (.gogoproto.moretags) = "yaml:\"proof_commitment\""];</code>
     */
    protected $proof_commitment = '';
    /**
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 3 [json_name = "proofHeight", (.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:\"proof_height\""];</code>
     */
    protected $proof_height = null;
    /**
     * Generated from protobuf field <code>string signer = 4 [json_name = "signer"];</code>
     */
    protected $signer = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ibc\Core\Channel\V1\Packet $packet
     *     @type string $proof_commitment
     *     @type \Ibc\Core\Client\V1\Height $proof_height
     *     @type string $signer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Core\Channel\V1\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ibc.core.channel.v1.Packet packet = 1 [json_name = "packet", (.gogoproto.nullable) = false];</code>
     * @return \Ibc\Core\Channel\V1\Packet|null
     */
    public function getPacket()
    {
        return $this->packet;
    }

    public function hasPacket()
    {
        return isset($this->packet);
    }

    public function clearPacket()
    {
        unset($this->packet);
    }

    /**
     * Generated from protobuf field <code>.ibc.core.channel.v1.Packet packet = 1 [json_name = "packet", (.gogoproto.nullable) = false];</code>
     * @param \Ibc\Core\Channel\V1\Packet $var
     * @return $this
     */
    public function setPacket($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Core\Channel\V1\Packet::class);
        $this->packet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes proof_commitment = 2 [json_name = "proofCommitment", (.gogoproto.moretags) = "yaml:\"proof_commitment\""];</code>
     * @return string
     */
    public function getProofCommitment()
    {
        return $this->proof_commitment;
    }

    /**
     * Generated from protobuf field <code>bytes proof_commitment = 2 [json_name = "proofCommitment", (.gogoproto.moretags) = "yaml:\"proof_commitment\""];</code>
     * @param string $var
     * @return $this
     */
    public function setProofCommitment($var)
    {
        GPBUtil::checkString($var, False);
        $this->proof_commitment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 3 [json_name = "proofHeight", (.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:\"proof_height\""];</code>
     * @return \Ibc\Core\Client\V1\Height|null
     */
    public function getProofHeight()
    {
        return $this->proof_height;
    }

    public function hasProofHeight()
    {
        return isset($this->proof_height);
    }

    public function clearProofHeight()
    {
        unset($this->proof_height);
    }

    /**
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 3 [json_name = "proofHeight", (.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:\"proof_height\""];</code>
     * @param \Ibc\Core\Client\V1\Height $var
     * @return $this
     */
    public function setProofHeight($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Core\Client\V1\Height::class);
        $this->proof_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signer = 4 [json_name = "signer"];</code>
     * @return string
     */
    public function getSigner()
    {
        return $this->signer;
    }

    /**
     * Generated from protobuf field <code>string signer = 4 [json_name = "signer"];</code>
     * @param string $var
     * @return $this
     */
    public function setSigner($var)
    {
        GPBUtil::checkString($var, True);
        $this->signer = $var;

        return $this;
    }

}

