<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/channel/v1/query.proto

namespace Ibc\Core\Channel\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryPacketAcknowledgementsRequest is the request type for the
 * Query/QueryPacketCommitments RPC method
 *
 * Generated from protobuf message <code>ibc.core.channel.v1.QueryPacketAcknowledgementsRequest</code>
 */
class QueryPacketAcknowledgementsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * port unique identifier
     *
     * Generated from protobuf field <code>string port_id = 1 [json_name = "portId"];</code>
     */
    protected $port_id = '';
    /**
     * channel unique identifier
     *
     * Generated from protobuf field <code>string channel_id = 2 [json_name = "channelId"];</code>
     */
    protected $channel_id = '';
    /**
     * pagination request
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageRequest pagination = 3 [json_name = "pagination"];</code>
     */
    protected $pagination = null;
    /**
     * list of packet sequences
     *
     * Generated from protobuf field <code>repeated uint64 packet_commitment_sequences = 4 [json_name = "packetCommitmentSequences"];</code>
     */
    private $packet_commitment_sequences;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $port_id
     *           port unique identifier
     *     @type string $channel_id
     *           channel unique identifier
     *     @type \Cosmos\Base\Query\V1beta1\PageRequest $pagination
     *           pagination request
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $packet_commitment_sequences
     *           list of packet sequences
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Core\Channel\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * port unique identifier
     *
     * Generated from protobuf field <code>string port_id = 1 [json_name = "portId"];</code>
     * @return string
     */
    public function getPortId()
    {
        return $this->port_id;
    }

    /**
     * port unique identifier
     *
     * Generated from protobuf field <code>string port_id = 1 [json_name = "portId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPortId($var)
    {
        GPBUtil::checkString($var, True);
        $this->port_id = $var;

        return $this;
    }

    /**
     * channel unique identifier
     *
     * Generated from protobuf field <code>string channel_id = 2 [json_name = "channelId"];</code>
     * @return string
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }

    /**
     * channel unique identifier
     *
     * Generated from protobuf field <code>string channel_id = 2 [json_name = "channelId"];</code>
     * @param string $var
     * @return $this
     */
    public function setChannelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel_id = $var;

        return $this;
    }

    /**
     * pagination request
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageRequest pagination = 3 [json_name = "pagination"];</code>
     * @return \Cosmos\Base\Query\V1beta1\PageRequest|null
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    public function hasPagination()
    {
        return isset($this->pagination);
    }

    public function clearPagination()
    {
        unset($this->pagination);
    }

    /**
     * pagination request
     *
     * Generated from protobuf field <code>.cosmos.base.query.v1beta1.PageRequest pagination = 3 [json_name = "pagination"];</code>
     * @param \Cosmos\Base\Query\V1beta1\PageRequest $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Cosmos\Base\Query\V1beta1\PageRequest::class);
        $this->pagination = $var;

        return $this;
    }

    /**
     * list of packet sequences
     *
     * Generated from protobuf field <code>repeated uint64 packet_commitment_sequences = 4 [json_name = "packetCommitmentSequences"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPacketCommitmentSequences()
    {
        return $this->packet_commitment_sequences;
    }

    /**
     * list of packet sequences
     *
     * Generated from protobuf field <code>repeated uint64 packet_commitment_sequences = 4 [json_name = "packetCommitmentSequences"];</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPacketCommitmentSequences($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->packet_commitment_sequences = $arr;

        return $this;
    }

}

