<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/channel/v1/query.proto

namespace Ibc\Core\Channel\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QuerySequenceResponse is the request type for the
 * Query/QueryNextSequenceReceiveResponse RPC method
 *
 * Generated from protobuf message <code>ibc.core.channel.v1.QueryNextSequenceReceiveResponse</code>
 */
class QueryNextSequenceReceiveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * next sequence receive number
     *
     * Generated from protobuf field <code>uint64 next_sequence_receive = 1 [json_name = "nextSequenceReceive"];</code>
     */
    protected $next_sequence_receive = 0;
    /**
     * merkle proof of existence
     *
     * Generated from protobuf field <code>bytes proof = 2 [json_name = "proof"];</code>
     */
    protected $proof = '';
    /**
     * height at which the proof was retrieved
     *
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 3 [json_name = "proofHeight", (.gogoproto.nullable) = false];</code>
     */
    protected $proof_height = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $next_sequence_receive
     *           next sequence receive number
     *     @type string $proof
     *           merkle proof of existence
     *     @type \Ibc\Core\Client\V1\Height $proof_height
     *           height at which the proof was retrieved
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Core\Channel\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * next sequence receive number
     *
     * Generated from protobuf field <code>uint64 next_sequence_receive = 1 [json_name = "nextSequenceReceive"];</code>
     * @return int|string
     */
    public function getNextSequenceReceive()
    {
        return $this->next_sequence_receive;
    }

    /**
     * next sequence receive number
     *
     * Generated from protobuf field <code>uint64 next_sequence_receive = 1 [json_name = "nextSequenceReceive"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setNextSequenceReceive($var)
    {
        GPBUtil::checkUint64($var);
        $this->next_sequence_receive = $var;

        return $this;
    }

    /**
     * merkle proof of existence
     *
     * Generated from protobuf field <code>bytes proof = 2 [json_name = "proof"];</code>
     * @return string
     */
    public function getProof()
    {
        return $this->proof;
    }

    /**
     * merkle proof of existence
     *
     * Generated from protobuf field <code>bytes proof = 2 [json_name = "proof"];</code>
     * @param string $var
     * @return $this
     */
    public function setProof($var)
    {
        GPBUtil::checkString($var, False);
        $this->proof = $var;

        return $this;
    }

    /**
     * height at which the proof was retrieved
     *
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 3 [json_name = "proofHeight", (.gogoproto.nullable) = false];</code>
     * @return \Ibc\Core\Client\V1\Height|null
     */
    public function getProofHeight()
    {
        return $this->proof_height;
    }

    public function hasProofHeight()
    {
        return isset($this->proof_height);
    }

    public function clearProofHeight()
    {
        unset($this->proof_height);
    }

    /**
     * height at which the proof was retrieved
     *
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 3 [json_name = "proofHeight", (.gogoproto.nullable) = false];</code>
     * @param \Ibc\Core\Client\V1\Height $var
     * @return $this
     */
    public function setProofHeight($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Core\Client\V1\Height::class);
        $this->proof_height = $var;

        return $this;
    }

}

