<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/base/tendermint/v1beta1/query.proto

namespace Cosmos\Base\Tendermint\V1beta1\GPBMetadata;

class Query
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \Google\Api\GPBMetadata\Annotations::initOnce();
        \Tendermint\P2p\GPBMetadata\Types::initOnce();
        \Tendermint\Types\GPBMetadata\Block::initOnce();
        \Tendermint\Types\GPBMetadata\Types::initOnce();
        \Cosmos\Base\Query\V1beta1\GPBMetadata\Pagination::initOnce();
        $pool->internalAddGeneratedFile(
            '
¨
*cosmos/base/tendermint/v1beta1/query.protocosmos.base.tendermint.v1beta1google/api/annotations.prototendermint/p2p/types.prototendermint/types/block.prototendermint/types/types.proto*cosmos/base/query/v1beta1/pagination.proto"€
GetValidatorSetByHeightRequest
height (RheightF

pagination (2&.cosmos.base.query.v1beta1.PageRequestR
pagination"Ø
GetValidatorSetByHeightResponse!
block_height (RblockHeightI

validators (2).cosmos.base.tendermint.v1beta1.ValidatorR
validatorsG

pagination (2\'.cosmos.base.query.v1beta1.PageResponseR
pagination"f
GetLatestValidatorSetRequestF

pagination (2&.cosmos.base.query.v1beta1.PageRequestR
pagination"Ö
GetLatestValidatorSetResponse!
block_height (RblockHeightI

validators (2).cosmos.base.tendermint.v1beta1.ValidatorR
validatorsG

pagination (2\'.cosmos.base.query.v1beta1.PageResponseR
pagination"¤
	Validator
address (	Raddress-
pub_key (2.google.protobuf.AnyRpubKey!
voting_power (RvotingPower+
proposer_priority (RproposerPriority"1
GetBlockByHeightRequest
height (Rheight"
GetBlockByHeightResponse4
block_id (2.tendermint.types.BlockIDRblockId-
block (2.tendermint.types.BlockRblock"
GetLatestBlockRequest"}
GetLatestBlockResponse4
block_id (2.tendermint.types.BlockIDRblockId-
block (2.tendermint.types.BlockRblock"
GetSyncingRequest".
GetSyncingResponse
syncing (Rsyncing"
GetNodeInfoRequest"À
GetNodeInfoResponseK
default_node_info (2.tendermint.p2p.DefaultNodeInfoRdefaultNodeInfo\\
application_version (2+.cosmos.base.tendermint.v1beta1.VersionInfoRapplicationVersion"¨
VersionInfo
name (	Rname
app_name (	RappName
version (	Rversion

git_commit (	R	gitCommit

build_tags (	R	buildTags

go_version (	R	goVersionE

build_deps (2&.cosmos.base.tendermint.v1beta1.ModuleR	buildDeps,
cosmos_sdk_version (	RcosmosSdkVersion"H
Module
path (	Rpath
version (	Rversion
sum (	Rsum2ˆ	
Service©
GetNodeInfo2.cosmos.base.tendermint.v1beta1.GetNodeInfoRequest3.cosmos.base.tendermint.v1beta1.GetNodeInfoResponse"1‚Óä“+)/cosmos/base/tendermint/v1beta1/node_info¤

GetSyncing1.cosmos.base.tendermint.v1beta1.GetSyncingRequest2.cosmos.base.tendermint.v1beta1.GetSyncingResponse"/‚Óä“)\'/cosmos/base/tendermint/v1beta1/syncing¶
GetLatestBlock5.cosmos.base.tendermint.v1beta1.GetLatestBlockRequest6.cosmos.base.tendermint.v1beta1.GetLatestBlockResponse"5‚Óä“/-/cosmos/base/tendermint/v1beta1/blocks/latest¾
GetBlockByHeight7.cosmos.base.tendermint.v1beta1.GetBlockByHeightRequest8.cosmos.base.tendermint.v1beta1.GetBlockByHeightResponse"7‚Óä“1//cosmos/base/tendermint/v1beta1/blocks/{height}Ò
GetLatestValidatorSet<.cosmos.base.tendermint.v1beta1.GetLatestValidatorSetRequest=.cosmos.base.tendermint.v1beta1.GetLatestValidatorSetResponse"<‚Óä“64/cosmos/base/tendermint/v1beta1/validatorsets/latestÚ
GetValidatorSetByHeight>.cosmos.base.tendermint.v1beta1.GetValidatorSetByHeightRequest?.cosmos.base.tendermint.v1beta1.GetValidatorSetByHeightResponse">‚Óä“86/cosmos/base/tendermint/v1beta1/validatorsets/{height}Bÿ
"com.cosmos.base.tendermint.v1beta1B
QueryProtoPZ2github.com/cosmos/cosmos-sdk/client/grpc/tmservice¢CBTªCosmos.Base.Tendermint.V1beta1ÊCosmos\\Base\\Tendermint\\V1beta1â*Cosmos\\Base\\Tendermint\\V1beta1\\GPBMetadataê!Cosmos::Base::Tendermint::V1beta1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

