<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/base/tendermint/v1beta1/query.proto

namespace Cosmos\Base\Tendermint\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Validator is the type for the validator-set.
 *
 * Generated from protobuf message <code>cosmos.base.tendermint.v1beta1.Validator</code>
 */
class Validator extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1 [json_name = "address"];</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Any pub_key = 2 [json_name = "pubKey"];</code>
     */
    protected $pub_key = null;
    /**
     * Generated from protobuf field <code>int64 voting_power = 3 [json_name = "votingPower"];</code>
     */
    protected $voting_power = 0;
    /**
     * Generated from protobuf field <code>int64 proposer_priority = 4 [json_name = "proposerPriority"];</code>
     */
    protected $proposer_priority = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type \Google\Protobuf\Any $pub_key
     *     @type int|string $voting_power
     *     @type int|string $proposer_priority
     * }
     */
    public function __construct($data = NULL) {
        \Cosmos\Base\Tendermint\V1beta1\GPBMetadata\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1 [json_name = "address"];</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1 [json_name = "address"];</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any pub_key = 2 [json_name = "pubKey"];</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getPubKey()
    {
        return $this->pub_key;
    }

    public function hasPubKey()
    {
        return isset($this->pub_key);
    }

    public function clearPubKey()
    {
        unset($this->pub_key);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any pub_key = 2 [json_name = "pubKey"];</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setPubKey($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->pub_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 voting_power = 3 [json_name = "votingPower"];</code>
     * @return int|string
     */
    public function getVotingPower()
    {
        return $this->voting_power;
    }

    /**
     * Generated from protobuf field <code>int64 voting_power = 3 [json_name = "votingPower"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setVotingPower($var)
    {
        GPBUtil::checkInt64($var);
        $this->voting_power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 proposer_priority = 4 [json_name = "proposerPriority"];</code>
     * @return int|string
     */
    public function getProposerPriority()
    {
        return $this->proposer_priority;
    }

    /**
     * Generated from protobuf field <code>int64 proposer_priority = 4 [json_name = "proposerPriority"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setProposerPriority($var)
    {
        GPBUtil::checkInt64($var);
        $this->proposer_priority = $var;

        return $this;
    }

}

